//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ePlatBack.Models.ccservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BankServiceSoap", Namespace="https://resortcom.com/ccservice")]
    public partial class BankService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private AuthHeader authHeaderValueField;
        
        private System.Threading.SendOrPostCallback AuthorReversalOperationCompleted;
        
        private System.Threading.SendOrPostCallback CardAuthorReqExtOperationCompleted;
        
        private System.Threading.SendOrPostCallback CardAuthorReqOperationCompleted;
        
        private System.Threading.SendOrPostCallback PmtCardAuthOperationCompleted;
        
        private System.Threading.SendOrPostCallback CV2PmtCardAuthOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResortCheckOutReqOperationCompleted;
        
        private System.Threading.SendOrPostCallback ResortCheckInReqOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthorizeCCOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthorizeCRMCCOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreditCardProcessAuthorReqOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreditCardProcessAuthorReversalOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCardAuthStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMerchantByIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BankService() {
            this.Url = global::ePlatBack.Models.Properties.Settings.Default.ePlatBack_Models_ccservice_BankService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public AuthHeader AuthHeaderValue {
            get {
                return this.authHeaderValueField;
            }
            set {
                this.authHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AuthorReversalCompletedEventHandler AuthorReversalCompleted;
        
        /// <remarks/>
        public event CardAuthorReqExtCompletedEventHandler CardAuthorReqExtCompleted;
        
        /// <remarks/>
        public event CardAuthorReqCompletedEventHandler CardAuthorReqCompleted;
        
        /// <remarks/>
        public event PmtCardAuthCompletedEventHandler PmtCardAuthCompleted;
        
        /// <remarks/>
        public event CV2PmtCardAuthCompletedEventHandler CV2PmtCardAuthCompleted;
        
        /// <remarks/>
        public event ResortCheckOutReqCompletedEventHandler ResortCheckOutReqCompleted;
        
        /// <remarks/>
        public event ResortCheckInReqCompletedEventHandler ResortCheckInReqCompleted;
        
        /// <remarks/>
        public event AuthorizeCCCompletedEventHandler AuthorizeCCCompleted;
        
        /// <remarks/>
        public event AuthorizeCRMCCCompletedEventHandler AuthorizeCRMCCCompleted;
        
        /// <remarks/>
        public event CreditCardProcessAuthorReqCompletedEventHandler CreditCardProcessAuthorReqCompleted;
        
        /// <remarks/>
        public event CreditCardProcessAuthorReversalCompletedEventHandler CreditCardProcessAuthorReversalCompleted;
        
        /// <remarks/>
        public event UpdateCardAuthStatusCompletedEventHandler UpdateCardAuthStatusCompleted;
        
        /// <remarks/>
        public event GetMerchantByIdCompletedEventHandler GetMerchantByIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://resortcom.com/ccservice/AuthorReversal", RequestNamespace="https://resortcom.com/ccservice", ResponseNamespace="https://resortcom.com/ccservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAuthorizationPubResponse AuthorReversal(AuthorizeRev AutRev) {
            object[] results = this.Invoke("AuthorReversal", new object[] {
                        AutRev});
            return ((CardAuthorizationPubResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AuthorReversalAsync(AuthorizeRev AutRev) {
            this.AuthorReversalAsync(AutRev, null);
        }
        
        /// <remarks/>
        public void AuthorReversalAsync(AuthorizeRev AutRev, object userState) {
            if ((this.AuthorReversalOperationCompleted == null)) {
                this.AuthorReversalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthorReversalOperationCompleted);
            }
            this.InvokeAsync("AuthorReversal", new object[] {
                        AutRev}, this.AuthorReversalOperationCompleted, userState);
        }
        
        private void OnAuthorReversalOperationCompleted(object arg) {
            if ((this.AuthorReversalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthorReversalCompleted(this, new AuthorReversalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://resortcom.com/ccservice/CardAuthorReqExt", RequestNamespace="https://resortcom.com/ccservice", ResponseNamespace="https://resortcom.com/ccservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAuthorizationPubResponse CardAuthorReqExt(CardAuthorizReq CardAutReq, ExtendedInfo ExtendInfo) {
            object[] results = this.Invoke("CardAuthorReqExt", new object[] {
                        CardAutReq,
                        ExtendInfo});
            return ((CardAuthorizationPubResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CardAuthorReqExtAsync(CardAuthorizReq CardAutReq, ExtendedInfo ExtendInfo) {
            this.CardAuthorReqExtAsync(CardAutReq, ExtendInfo, null);
        }
        
        /// <remarks/>
        public void CardAuthorReqExtAsync(CardAuthorizReq CardAutReq, ExtendedInfo ExtendInfo, object userState) {
            if ((this.CardAuthorReqExtOperationCompleted == null)) {
                this.CardAuthorReqExtOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCardAuthorReqExtOperationCompleted);
            }
            this.InvokeAsync("CardAuthorReqExt", new object[] {
                        CardAutReq,
                        ExtendInfo}, this.CardAuthorReqExtOperationCompleted, userState);
        }
        
        private void OnCardAuthorReqExtOperationCompleted(object arg) {
            if ((this.CardAuthorReqExtCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CardAuthorReqExtCompleted(this, new CardAuthorReqExtCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://resortcom.com/ccservice/CardAuthorReq", RequestNamespace="https://resortcom.com/ccservice", ResponseNamespace="https://resortcom.com/ccservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAuthorizationPubResponse CardAuthorReq(CardAuthorizReq CardAutReq) {
            object[] results = this.Invoke("CardAuthorReq", new object[] {
                        CardAutReq});
            return ((CardAuthorizationPubResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CardAuthorReqAsync(CardAuthorizReq CardAutReq) {
            this.CardAuthorReqAsync(CardAutReq, null);
        }
        
        /// <remarks/>
        public void CardAuthorReqAsync(CardAuthorizReq CardAutReq, object userState) {
            if ((this.CardAuthorReqOperationCompleted == null)) {
                this.CardAuthorReqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCardAuthorReqOperationCompleted);
            }
            this.InvokeAsync("CardAuthorReq", new object[] {
                        CardAutReq}, this.CardAuthorReqOperationCompleted, userState);
        }
        
        private void OnCardAuthorReqOperationCompleted(object arg) {
            if ((this.CardAuthorReqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CardAuthorReqCompleted(this, new CardAuthorReqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://resortcom.com/ccservice/PmtCardAuth", RequestNamespace="https://resortcom.com/ccservice", ResponseNamespace="https://resortcom.com/ccservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAuthorizationPubResponse PmtCardAuth(CardAuthorizPmt CardAutPmt) {
            object[] results = this.Invoke("PmtCardAuth", new object[] {
                        CardAutPmt});
            return ((CardAuthorizationPubResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PmtCardAuthAsync(CardAuthorizPmt CardAutPmt) {
            this.PmtCardAuthAsync(CardAutPmt, null);
        }
        
        /// <remarks/>
        public void PmtCardAuthAsync(CardAuthorizPmt CardAutPmt, object userState) {
            if ((this.PmtCardAuthOperationCompleted == null)) {
                this.PmtCardAuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPmtCardAuthOperationCompleted);
            }
            this.InvokeAsync("PmtCardAuth", new object[] {
                        CardAutPmt}, this.PmtCardAuthOperationCompleted, userState);
        }
        
        private void OnPmtCardAuthOperationCompleted(object arg) {
            if ((this.PmtCardAuthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PmtCardAuthCompleted(this, new PmtCardAuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://resortcom.com/ccservice/CV2PmtCardAuth", RequestNamespace="https://resortcom.com/ccservice", ResponseNamespace="https://resortcom.com/ccservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAuthorizationPubResponse CV2PmtCardAuth(CV2CardAuthorizPmt CardAutPmt) {
            object[] results = this.Invoke("CV2PmtCardAuth", new object[] {
                        CardAutPmt});
            return ((CardAuthorizationPubResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CV2PmtCardAuthAsync(CV2CardAuthorizPmt CardAutPmt) {
            this.CV2PmtCardAuthAsync(CardAutPmt, null);
        }
        
        /// <remarks/>
        public void CV2PmtCardAuthAsync(CV2CardAuthorizPmt CardAutPmt, object userState) {
            if ((this.CV2PmtCardAuthOperationCompleted == null)) {
                this.CV2PmtCardAuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCV2PmtCardAuthOperationCompleted);
            }
            this.InvokeAsync("CV2PmtCardAuth", new object[] {
                        CardAutPmt}, this.CV2PmtCardAuthOperationCompleted, userState);
        }
        
        private void OnCV2PmtCardAuthOperationCompleted(object arg) {
            if ((this.CV2PmtCardAuthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CV2PmtCardAuthCompleted(this, new CV2PmtCardAuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://resortcom.com/ccservice/ResortCheckOutReq", RequestNamespace="https://resortcom.com/ccservice", ResponseNamespace="https://resortcom.com/ccservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAuthorizationPubResponse ResortCheckOutReq(ResortCheckOut RstChkOutReq) {
            object[] results = this.Invoke("ResortCheckOutReq", new object[] {
                        RstChkOutReq});
            return ((CardAuthorizationPubResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ResortCheckOutReqAsync(ResortCheckOut RstChkOutReq) {
            this.ResortCheckOutReqAsync(RstChkOutReq, null);
        }
        
        /// <remarks/>
        public void ResortCheckOutReqAsync(ResortCheckOut RstChkOutReq, object userState) {
            if ((this.ResortCheckOutReqOperationCompleted == null)) {
                this.ResortCheckOutReqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResortCheckOutReqOperationCompleted);
            }
            this.InvokeAsync("ResortCheckOutReq", new object[] {
                        RstChkOutReq}, this.ResortCheckOutReqOperationCompleted, userState);
        }
        
        private void OnResortCheckOutReqOperationCompleted(object arg) {
            if ((this.ResortCheckOutReqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResortCheckOutReqCompleted(this, new ResortCheckOutReqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://resortcom.com/ccservice/ResortCheckInReq", RequestNamespace="https://resortcom.com/ccservice", ResponseNamespace="https://resortcom.com/ccservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAuthorizationPubResponse ResortCheckInReq(ResortCheckIn RstChkInReq) {
            object[] results = this.Invoke("ResortCheckInReq", new object[] {
                        RstChkInReq});
            return ((CardAuthorizationPubResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ResortCheckInReqAsync(ResortCheckIn RstChkInReq) {
            this.ResortCheckInReqAsync(RstChkInReq, null);
        }
        
        /// <remarks/>
        public void ResortCheckInReqAsync(ResortCheckIn RstChkInReq, object userState) {
            if ((this.ResortCheckInReqOperationCompleted == null)) {
                this.ResortCheckInReqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResortCheckInReqOperationCompleted);
            }
            this.InvokeAsync("ResortCheckInReq", new object[] {
                        RstChkInReq}, this.ResortCheckInReqOperationCompleted, userState);
        }
        
        private void OnResortCheckInReqOperationCompleted(object arg) {
            if ((this.ResortCheckInReqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResortCheckInReqCompleted(this, new ResortCheckInReqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://resortcom.com/ccservice/AuthorizeCC", RequestNamespace="https://resortcom.com/ccservice", ResponseNamespace="https://resortcom.com/ccservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAuthorizationPubResponse AuthorizeCC(CardAuthorizationPub AuthDataPub) {
            object[] results = this.Invoke("AuthorizeCC", new object[] {
                        AuthDataPub});
            return ((CardAuthorizationPubResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AuthorizeCCAsync(CardAuthorizationPub AuthDataPub) {
            this.AuthorizeCCAsync(AuthDataPub, null);
        }
        
        /// <remarks/>
        public void AuthorizeCCAsync(CardAuthorizationPub AuthDataPub, object userState) {
            if ((this.AuthorizeCCOperationCompleted == null)) {
                this.AuthorizeCCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthorizeCCOperationCompleted);
            }
            this.InvokeAsync("AuthorizeCC", new object[] {
                        AuthDataPub}, this.AuthorizeCCOperationCompleted, userState);
        }
        
        private void OnAuthorizeCCOperationCompleted(object arg) {
            if ((this.AuthorizeCCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthorizeCCCompleted(this, new AuthorizeCCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://resortcom.com/ccservice/AuthorizeCRMCC", RequestNamespace="https://resortcom.com/ccservice", ResponseNamespace="https://resortcom.com/ccservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAuthorizationPubResponse AuthorizeCRMCC(CardAuthorizationCRM AuthCRM, out CRMAcctInfo CRMInfo) {
            object[] results = this.Invoke("AuthorizeCRMCC", new object[] {
                        AuthCRM});
            CRMInfo = ((CRMAcctInfo)(results[1]));
            return ((CardAuthorizationPubResponse)(results[0]));
        }
        
        /// <remarks/>
        public void AuthorizeCRMCCAsync(CardAuthorizationCRM AuthCRM) {
            this.AuthorizeCRMCCAsync(AuthCRM, null);
        }
        
        /// <remarks/>
        public void AuthorizeCRMCCAsync(CardAuthorizationCRM AuthCRM, object userState) {
            if ((this.AuthorizeCRMCCOperationCompleted == null)) {
                this.AuthorizeCRMCCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthorizeCRMCCOperationCompleted);
            }
            this.InvokeAsync("AuthorizeCRMCC", new object[] {
                        AuthCRM}, this.AuthorizeCRMCCOperationCompleted, userState);
        }
        
        private void OnAuthorizeCRMCCOperationCompleted(object arg) {
            if ((this.AuthorizeCRMCCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthorizeCRMCCCompleted(this, new AuthorizeCRMCCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://resortcom.com/ccservice/CreditCardProcessAuthorReq", RequestNamespace="https://resortcom.com/ccservice", ResponseNamespace="https://resortcom.com/ccservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAuthorizationPubResponse CreditCardProcessAuthorReq(string strCCAuthXML) {
            object[] results = this.Invoke("CreditCardProcessAuthorReq", new object[] {
                        strCCAuthXML});
            return ((CardAuthorizationPubResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreditCardProcessAuthorReqAsync(string strCCAuthXML) {
            this.CreditCardProcessAuthorReqAsync(strCCAuthXML, null);
        }
        
        /// <remarks/>
        public void CreditCardProcessAuthorReqAsync(string strCCAuthXML, object userState) {
            if ((this.CreditCardProcessAuthorReqOperationCompleted == null)) {
                this.CreditCardProcessAuthorReqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreditCardProcessAuthorReqOperationCompleted);
            }
            this.InvokeAsync("CreditCardProcessAuthorReq", new object[] {
                        strCCAuthXML}, this.CreditCardProcessAuthorReqOperationCompleted, userState);
        }
        
        private void OnCreditCardProcessAuthorReqOperationCompleted(object arg) {
            if ((this.CreditCardProcessAuthorReqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreditCardProcessAuthorReqCompleted(this, new CreditCardProcessAuthorReqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://resortcom.com/ccservice/CreditCardProcessAuthorReversal", RequestNamespace="https://resortcom.com/ccservice", ResponseNamespace="https://resortcom.com/ccservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAuthorizationPubResponse CreditCardProcessAuthorReversal(string strCCRevXML) {
            object[] results = this.Invoke("CreditCardProcessAuthorReversal", new object[] {
                        strCCRevXML});
            return ((CardAuthorizationPubResponse)(results[0]));
        }
        
        /// <remarks/>
        public void CreditCardProcessAuthorReversalAsync(string strCCRevXML) {
            this.CreditCardProcessAuthorReversalAsync(strCCRevXML, null);
        }
        
        /// <remarks/>
        public void CreditCardProcessAuthorReversalAsync(string strCCRevXML, object userState) {
            if ((this.CreditCardProcessAuthorReversalOperationCompleted == null)) {
                this.CreditCardProcessAuthorReversalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreditCardProcessAuthorReversalOperationCompleted);
            }
            this.InvokeAsync("CreditCardProcessAuthorReversal", new object[] {
                        strCCRevXML}, this.CreditCardProcessAuthorReversalOperationCompleted, userState);
        }
        
        private void OnCreditCardProcessAuthorReversalOperationCompleted(object arg) {
            if ((this.CreditCardProcessAuthorReversalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreditCardProcessAuthorReversalCompleted(this, new CreditCardProcessAuthorReversalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://resortcom.com/ccservice/UpdateCardAuthStatus", RequestNamespace="https://resortcom.com/ccservice", ResponseNamespace="https://resortcom.com/ccservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CardAuthorizationPubResponse UpdateCardAuthStatus(int p_nCardAuthNum, int p_nAuthStatus) {
            object[] results = this.Invoke("UpdateCardAuthStatus", new object[] {
                        p_nCardAuthNum,
                        p_nAuthStatus});
            return ((CardAuthorizationPubResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateCardAuthStatusAsync(int p_nCardAuthNum, int p_nAuthStatus) {
            this.UpdateCardAuthStatusAsync(p_nCardAuthNum, p_nAuthStatus, null);
        }
        
        /// <remarks/>
        public void UpdateCardAuthStatusAsync(int p_nCardAuthNum, int p_nAuthStatus, object userState) {
            if ((this.UpdateCardAuthStatusOperationCompleted == null)) {
                this.UpdateCardAuthStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCardAuthStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateCardAuthStatus", new object[] {
                        p_nCardAuthNum,
                        p_nAuthStatus}, this.UpdateCardAuthStatusOperationCompleted, userState);
        }
        
        private void OnUpdateCardAuthStatusOperationCompleted(object arg) {
            if ((this.UpdateCardAuthStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCardAuthStatusCompleted(this, new UpdateCardAuthStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://resortcom.com/ccservice/GetMerchantById", RequestNamespace="https://resortcom.com/ccservice", ResponseNamespace="https://resortcom.com/ccservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetMerchantById(int p_nMerchantId, out string xmlResponse) {
            object[] results = this.Invoke("GetMerchantById", new object[] {
                        p_nMerchantId});
            xmlResponse = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetMerchantByIdAsync(int p_nMerchantId) {
            this.GetMerchantByIdAsync(p_nMerchantId, null);
        }
        
        /// <remarks/>
        public void GetMerchantByIdAsync(int p_nMerchantId, object userState) {
            if ((this.GetMerchantByIdOperationCompleted == null)) {
                this.GetMerchantByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMerchantByIdOperationCompleted);
            }
            this.InvokeAsync("GetMerchantById", new object[] {
                        p_nMerchantId}, this.GetMerchantByIdOperationCompleted, userState);
        }
        
        private void OnGetMerchantByIdOperationCompleted(object arg) {
            if ((this.GetMerchantByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMerchantByIdCompleted(this, new GetMerchantByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://resortcom.com/ccservice")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://resortcom.com/ccservice", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://resortcom.com/ccservice")]
    public partial class CRMAcctInfo {
        
        private string bank_NameField;
        
        private string currency_TypeField;
        
        private string auth_StatusField;
        
        private string invoice_NumField;
        
        private string merchant_NameField;
        
        private string member_Account_NumField;
        
        private string card_Holder_NameField;
        
        private string address_VerifiedField;
        
        private string zip_VerifiedField;
        
        private string user_NameField;
        
        private string auth_DateField;
        
        private double auth_AmountField;
        
        /// <remarks/>
        public string Bank_Name {
            get {
                return this.bank_NameField;
            }
            set {
                this.bank_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Currency_Type {
            get {
                return this.currency_TypeField;
            }
            set {
                this.currency_TypeField = value;
            }
        }
        
        /// <remarks/>
        public string Auth_Status {
            get {
                return this.auth_StatusField;
            }
            set {
                this.auth_StatusField = value;
            }
        }
        
        /// <remarks/>
        public string Invoice_Num {
            get {
                return this.invoice_NumField;
            }
            set {
                this.invoice_NumField = value;
            }
        }
        
        /// <remarks/>
        public string Merchant_Name {
            get {
                return this.merchant_NameField;
            }
            set {
                this.merchant_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Member_Account_Num {
            get {
                return this.member_Account_NumField;
            }
            set {
                this.member_Account_NumField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder_Name {
            get {
                return this.card_Holder_NameField;
            }
            set {
                this.card_Holder_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Address_Verified {
            get {
                return this.address_VerifiedField;
            }
            set {
                this.address_VerifiedField = value;
            }
        }
        
        /// <remarks/>
        public string Zip_Verified {
            get {
                return this.zip_VerifiedField;
            }
            set {
                this.zip_VerifiedField = value;
            }
        }
        
        /// <remarks/>
        public string User_Name {
            get {
                return this.user_NameField;
            }
            set {
                this.user_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Auth_Date {
            get {
                return this.auth_DateField;
            }
            set {
                this.auth_DateField = value;
            }
        }
        
        /// <remarks/>
        public double Auth_Amount {
            get {
                return this.auth_AmountField;
            }
            set {
                this.auth_AmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://resortcom.com/ccservice")]
    public partial class CardAuthorizationCRM {
        
        private string card_HolderField;
        
        private string card_Holder_AddressField;
        
        private string card_Holder_ZipField;
        
        private string card_NumberField;
        
        private int card_TypeField;
        
        private string expiration_DateField;
        
        private double transaction_AmountField;
        
        private string authorization_ReferenceField;
        
        private int card_CV2_CodeField;
        
        private string card_CV2_ValueField;
        
        private int card_Class_CodeField;
        
        private int fraud_CodeField;
        
        private int months_DeferredField;
        
        private int number_PaymentsField;
        
        private int plan_TypeField;
        
        private int merchant_IdField;
        
        /// <remarks/>
        public string Card_Holder {
            get {
                return this.card_HolderField;
            }
            set {
                this.card_HolderField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder_Address {
            get {
                return this.card_Holder_AddressField;
            }
            set {
                this.card_Holder_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder_Zip {
            get {
                return this.card_Holder_ZipField;
            }
            set {
                this.card_Holder_ZipField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Number {
            get {
                return this.card_NumberField;
            }
            set {
                this.card_NumberField = value;
            }
        }
        
        /// <remarks/>
        public int Card_Type {
            get {
                return this.card_TypeField;
            }
            set {
                this.card_TypeField = value;
            }
        }
        
        /// <remarks/>
        public string Expiration_Date {
            get {
                return this.expiration_DateField;
            }
            set {
                this.expiration_DateField = value;
            }
        }
        
        /// <remarks/>
        public double Transaction_Amount {
            get {
                return this.transaction_AmountField;
            }
            set {
                this.transaction_AmountField = value;
            }
        }
        
        /// <remarks/>
        public string Authorization_Reference {
            get {
                return this.authorization_ReferenceField;
            }
            set {
                this.authorization_ReferenceField = value;
            }
        }
        
        /// <remarks/>
        public int Card_CV2_Code {
            get {
                return this.card_CV2_CodeField;
            }
            set {
                this.card_CV2_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Card_CV2_Value {
            get {
                return this.card_CV2_ValueField;
            }
            set {
                this.card_CV2_ValueField = value;
            }
        }
        
        /// <remarks/>
        public int Card_Class_Code {
            get {
                return this.card_Class_CodeField;
            }
            set {
                this.card_Class_CodeField = value;
            }
        }
        
        /// <remarks/>
        public int Fraud_Code {
            get {
                return this.fraud_CodeField;
            }
            set {
                this.fraud_CodeField = value;
            }
        }
        
        /// <remarks/>
        public int Months_Deferred {
            get {
                return this.months_DeferredField;
            }
            set {
                this.months_DeferredField = value;
            }
        }
        
        /// <remarks/>
        public int Number_Payments {
            get {
                return this.number_PaymentsField;
            }
            set {
                this.number_PaymentsField = value;
            }
        }
        
        /// <remarks/>
        public int Plan_Type {
            get {
                return this.plan_TypeField;
            }
            set {
                this.plan_TypeField = value;
            }
        }
        
        /// <remarks/>
        public int Merchant_Id {
            get {
                return this.merchant_IdField;
            }
            set {
                this.merchant_IdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://resortcom.com/ccservice")]
    public partial class CardAuthorizationPub {
        
        private string card_NumberField;
        
        private string expiration_DateField;
        
        private double transaction_AmountField;
        
        private string card_HolderField;
        
        private string card_Holder_AddressField;
        
        private string card_Holder_ZipField;
        
        private string reference_CodeField;
        
        /// <remarks/>
        public string Card_Number {
            get {
                return this.card_NumberField;
            }
            set {
                this.card_NumberField = value;
            }
        }
        
        /// <remarks/>
        public string Expiration_Date {
            get {
                return this.expiration_DateField;
            }
            set {
                this.expiration_DateField = value;
            }
        }
        
        /// <remarks/>
        public double Transaction_Amount {
            get {
                return this.transaction_AmountField;
            }
            set {
                this.transaction_AmountField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder {
            get {
                return this.card_HolderField;
            }
            set {
                this.card_HolderField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder_Address {
            get {
                return this.card_Holder_AddressField;
            }
            set {
                this.card_Holder_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder_Zip {
            get {
                return this.card_Holder_ZipField;
            }
            set {
                this.card_Holder_ZipField = value;
            }
        }
        
        /// <remarks/>
        public string Reference_Code {
            get {
                return this.reference_CodeField;
            }
            set {
                this.reference_CodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://resortcom.com/ccservice")]
    public partial class ResortCheckIn {
        
        private int user_IdField;
        
        private string card_NumberField;
        
        private string expiration_DateField;
        
        private double transaction_AmountField;
        
        private string nameField;
        
        private string addressField;
        
        private string zipField;
        
        private object invoiceField;
        
        /// <remarks/>
        public int User_Id {
            get {
                return this.user_IdField;
            }
            set {
                this.user_IdField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Number {
            get {
                return this.card_NumberField;
            }
            set {
                this.card_NumberField = value;
            }
        }
        
        /// <remarks/>
        public string Expiration_Date {
            get {
                return this.expiration_DateField;
            }
            set {
                this.expiration_DateField = value;
            }
        }
        
        /// <remarks/>
        public double Transaction_Amount {
            get {
                return this.transaction_AmountField;
            }
            set {
                this.transaction_AmountField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public object Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://resortcom.com/ccservice")]
    public partial class ResortCheckOut {
        
        private int user_IdField;
        
        private int check_In_Auth_NumberField;
        
        private string card_NumberField;
        
        private string expiration_DateField;
        
        private double transaction_AmountField;
        
        private string nameField;
        
        private string addressField;
        
        private string zipField;
        
        private object new_Invoice_OutField;
        
        /// <remarks/>
        public int User_Id {
            get {
                return this.user_IdField;
            }
            set {
                this.user_IdField = value;
            }
        }
        
        /// <remarks/>
        public int Check_In_Auth_Number {
            get {
                return this.check_In_Auth_NumberField;
            }
            set {
                this.check_In_Auth_NumberField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Number {
            get {
                return this.card_NumberField;
            }
            set {
                this.card_NumberField = value;
            }
        }
        
        /// <remarks/>
        public string Expiration_Date {
            get {
                return this.expiration_DateField;
            }
            set {
                this.expiration_DateField = value;
            }
        }
        
        /// <remarks/>
        public double Transaction_Amount {
            get {
                return this.transaction_AmountField;
            }
            set {
                this.transaction_AmountField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public object New_Invoice_Out {
            get {
                return this.new_Invoice_OutField;
            }
            set {
                this.new_Invoice_OutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://resortcom.com/ccservice")]
    public partial class CV2CardAuthorizPmt {
        
        private string card_NumberField;
        
        private string expiration_DateField;
        
        private double transaction_AmountField;
        
        private string authorization_ReferenceField;
        
        private int resortField;
        
        private int accountField;
        
        private string card_Holder_NameField;
        
        private string card_Holder_AddressField;
        
        private string card_Holder_ZipField;
        
        private int payment_typeField;
        
        private object invoiceField;
        
        private object address_MatchField;
        
        private object zip_MatchField;
        
        private object errMsgField;
        
        private int card_TypeField;
        
        private int card_CV2_CodeField;
        
        private string card_CV2_ValueField;
        
        private int card_Class_CodeField;
        
        private int fraud_CodeField;
        
        private int months_DeferredField;
        
        private int number_PaymentsField;
        
        private int plan_TypeField;
        
        /// <remarks/>
        public string Card_Number {
            get {
                return this.card_NumberField;
            }
            set {
                this.card_NumberField = value;
            }
        }
        
        /// <remarks/>
        public string Expiration_Date {
            get {
                return this.expiration_DateField;
            }
            set {
                this.expiration_DateField = value;
            }
        }
        
        /// <remarks/>
        public double Transaction_Amount {
            get {
                return this.transaction_AmountField;
            }
            set {
                this.transaction_AmountField = value;
            }
        }
        
        /// <remarks/>
        public string Authorization_Reference {
            get {
                return this.authorization_ReferenceField;
            }
            set {
                this.authorization_ReferenceField = value;
            }
        }
        
        /// <remarks/>
        public int Resort {
            get {
                return this.resortField;
            }
            set {
                this.resortField = value;
            }
        }
        
        /// <remarks/>
        public int Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder_Name {
            get {
                return this.card_Holder_NameField;
            }
            set {
                this.card_Holder_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder_Address {
            get {
                return this.card_Holder_AddressField;
            }
            set {
                this.card_Holder_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder_Zip {
            get {
                return this.card_Holder_ZipField;
            }
            set {
                this.card_Holder_ZipField = value;
            }
        }
        
        /// <remarks/>
        public int Payment_type {
            get {
                return this.payment_typeField;
            }
            set {
                this.payment_typeField = value;
            }
        }
        
        /// <remarks/>
        public object Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
            }
        }
        
        /// <remarks/>
        public object Address_Match {
            get {
                return this.address_MatchField;
            }
            set {
                this.address_MatchField = value;
            }
        }
        
        /// <remarks/>
        public object Zip_Match {
            get {
                return this.zip_MatchField;
            }
            set {
                this.zip_MatchField = value;
            }
        }
        
        /// <remarks/>
        public object errMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
            }
        }
        
        /// <remarks/>
        public int Card_Type {
            get {
                return this.card_TypeField;
            }
            set {
                this.card_TypeField = value;
            }
        }
        
        /// <remarks/>
        public int Card_CV2_Code {
            get {
                return this.card_CV2_CodeField;
            }
            set {
                this.card_CV2_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Card_CV2_Value {
            get {
                return this.card_CV2_ValueField;
            }
            set {
                this.card_CV2_ValueField = value;
            }
        }
        
        /// <remarks/>
        public int Card_Class_Code {
            get {
                return this.card_Class_CodeField;
            }
            set {
                this.card_Class_CodeField = value;
            }
        }
        
        /// <remarks/>
        public int Fraud_Code {
            get {
                return this.fraud_CodeField;
            }
            set {
                this.fraud_CodeField = value;
            }
        }
        
        /// <remarks/>
        public int Months_Deferred {
            get {
                return this.months_DeferredField;
            }
            set {
                this.months_DeferredField = value;
            }
        }
        
        /// <remarks/>
        public int Number_Payments {
            get {
                return this.number_PaymentsField;
            }
            set {
                this.number_PaymentsField = value;
            }
        }
        
        /// <remarks/>
        public int Plan_Type {
            get {
                return this.plan_TypeField;
            }
            set {
                this.plan_TypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://resortcom.com/ccservice")]
    public partial class CardAuthorizPmt {
        
        private string card_NumberField;
        
        private string expiration_DateField;
        
        private double transaction_AmountField;
        
        private string authorization_ReferenceField;
        
        private int resortField;
        
        private int accountField;
        
        private string card_Holder_NameField;
        
        private string card_Holder_AddressField;
        
        private string card_Holder_ZipField;
        
        private int payment_typeField;
        
        private object invoiceField;
        
        private object address_MatchField;
        
        private object zip_MatchField;
        
        private object errMsgField;
        
        /// <remarks/>
        public string Card_Number {
            get {
                return this.card_NumberField;
            }
            set {
                this.card_NumberField = value;
            }
        }
        
        /// <remarks/>
        public string Expiration_Date {
            get {
                return this.expiration_DateField;
            }
            set {
                this.expiration_DateField = value;
            }
        }
        
        /// <remarks/>
        public double Transaction_Amount {
            get {
                return this.transaction_AmountField;
            }
            set {
                this.transaction_AmountField = value;
            }
        }
        
        /// <remarks/>
        public string Authorization_Reference {
            get {
                return this.authorization_ReferenceField;
            }
            set {
                this.authorization_ReferenceField = value;
            }
        }
        
        /// <remarks/>
        public int Resort {
            get {
                return this.resortField;
            }
            set {
                this.resortField = value;
            }
        }
        
        /// <remarks/>
        public int Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder_Name {
            get {
                return this.card_Holder_NameField;
            }
            set {
                this.card_Holder_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder_Address {
            get {
                return this.card_Holder_AddressField;
            }
            set {
                this.card_Holder_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder_Zip {
            get {
                return this.card_Holder_ZipField;
            }
            set {
                this.card_Holder_ZipField = value;
            }
        }
        
        /// <remarks/>
        public int Payment_type {
            get {
                return this.payment_typeField;
            }
            set {
                this.payment_typeField = value;
            }
        }
        
        /// <remarks/>
        public object Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
            }
        }
        
        /// <remarks/>
        public object Address_Match {
            get {
                return this.address_MatchField;
            }
            set {
                this.address_MatchField = value;
            }
        }
        
        /// <remarks/>
        public object Zip_Match {
            get {
                return this.zip_MatchField;
            }
            set {
                this.zip_MatchField = value;
            }
        }
        
        /// <remarks/>
        public object errMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://resortcom.com/ccservice")]
    public partial class ExtendedInfo {
        
        private int ownerIDField;
        
        private int projectNbrField;
        
        private int partnerNbrField;
        
        private int lenderTypeField;
        
        private string receiptField;
        
        private string referenceField;
        
        private string reference2Field;
        
        private string ipField;
        
        /// <remarks/>
        public int OwnerID {
            get {
                return this.ownerIDField;
            }
            set {
                this.ownerIDField = value;
            }
        }
        
        /// <remarks/>
        public int ProjectNbr {
            get {
                return this.projectNbrField;
            }
            set {
                this.projectNbrField = value;
            }
        }
        
        /// <remarks/>
        public int PartnerNbr {
            get {
                return this.partnerNbrField;
            }
            set {
                this.partnerNbrField = value;
            }
        }
        
        /// <remarks/>
        public int LenderType {
            get {
                return this.lenderTypeField;
            }
            set {
                this.lenderTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Receipt {
            get {
                return this.receiptField;
            }
            set {
                this.receiptField = value;
            }
        }
        
        /// <remarks/>
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string Reference2 {
            get {
                return this.reference2Field;
            }
            set {
                this.reference2Field = value;
            }
        }
        
        /// <remarks/>
        public string IP {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://resortcom.com/ccservice")]
    public partial class CardAuthorizReq {
        
        private int primary_BankField;
        
        private int user_IdField;
        
        private int merchant_IdField;
        
        private string card_NumberField;
        
        private string expiration_DateField;
        
        private double transaction_AmountField;
        
        private string authorization_ReferenceField;
        
        private int resortField;
        
        private int accountField;
        
        private int versionField;
        
        private string card_Holder_NameField;
        
        private string card_Holder_AddressField;
        
        private string card_Holder_ZipField;
        
        private string conf_NumField;
        
        private object invoiceField;
        
        private object address_MatchField;
        
        private object zip_MatchField;
        
        /// <remarks/>
        public int Primary_Bank {
            get {
                return this.primary_BankField;
            }
            set {
                this.primary_BankField = value;
            }
        }
        
        /// <remarks/>
        public int User_Id {
            get {
                return this.user_IdField;
            }
            set {
                this.user_IdField = value;
            }
        }
        
        /// <remarks/>
        public int Merchant_Id {
            get {
                return this.merchant_IdField;
            }
            set {
                this.merchant_IdField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Number {
            get {
                return this.card_NumberField;
            }
            set {
                this.card_NumberField = value;
            }
        }
        
        /// <remarks/>
        public string Expiration_Date {
            get {
                return this.expiration_DateField;
            }
            set {
                this.expiration_DateField = value;
            }
        }
        
        /// <remarks/>
        public double Transaction_Amount {
            get {
                return this.transaction_AmountField;
            }
            set {
                this.transaction_AmountField = value;
            }
        }
        
        /// <remarks/>
        public string Authorization_Reference {
            get {
                return this.authorization_ReferenceField;
            }
            set {
                this.authorization_ReferenceField = value;
            }
        }
        
        /// <remarks/>
        public int Resort {
            get {
                return this.resortField;
            }
            set {
                this.resortField = value;
            }
        }
        
        /// <remarks/>
        public int Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
            }
        }
        
        /// <remarks/>
        public int Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder_Name {
            get {
                return this.card_Holder_NameField;
            }
            set {
                this.card_Holder_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder_Address {
            get {
                return this.card_Holder_AddressField;
            }
            set {
                this.card_Holder_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string Card_Holder_Zip {
            get {
                return this.card_Holder_ZipField;
            }
            set {
                this.card_Holder_ZipField = value;
            }
        }
        
        /// <remarks/>
        public string Conf_Num {
            get {
                return this.conf_NumField;
            }
            set {
                this.conf_NumField = value;
            }
        }
        
        /// <remarks/>
        public object Invoice {
            get {
                return this.invoiceField;
            }
            set {
                this.invoiceField = value;
            }
        }
        
        /// <remarks/>
        public object Address_Match {
            get {
                return this.address_MatchField;
            }
            set {
                this.address_MatchField = value;
            }
        }
        
        /// <remarks/>
        public object Zip_Match {
            get {
                return this.zip_MatchField;
            }
            set {
                this.zip_MatchField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://resortcom.com/ccservice")]
    public partial class CardAuthorizationPubResponse {
        
        private int error_CodeField;
        
        private string auth_CodeField;
        
        private string authorization_DateField;
        
        private double authorization_AmountField;
        
        /// <remarks/>
        public int Error_Code {
            get {
                return this.error_CodeField;
            }
            set {
                this.error_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Auth_Code {
            get {
                return this.auth_CodeField;
            }
            set {
                this.auth_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Authorization_Date {
            get {
                return this.authorization_DateField;
            }
            set {
                this.authorization_DateField = value;
            }
        }
        
        /// <remarks/>
        public double Authorization_Amount {
            get {
                return this.authorization_AmountField;
            }
            set {
                this.authorization_AmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://resortcom.com/ccservice")]
    public partial class AuthorizeRev {
        
        private int primary_BankField;
        
        private int auth_NumberField;
        
        private double transaction_AmountField;
        
        /// <remarks/>
        public int Primary_Bank {
            get {
                return this.primary_BankField;
            }
            set {
                this.primary_BankField = value;
            }
        }
        
        /// <remarks/>
        public int Auth_Number {
            get {
                return this.auth_NumberField;
            }
            set {
                this.auth_NumberField = value;
            }
        }
        
        /// <remarks/>
        public double Transaction_Amount {
            get {
                return this.transaction_AmountField;
            }
            set {
                this.transaction_AmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AuthorReversalCompletedEventHandler(object sender, AuthorReversalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthorReversalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthorReversalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAuthorizationPubResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAuthorizationPubResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CardAuthorReqExtCompletedEventHandler(object sender, CardAuthorReqExtCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CardAuthorReqExtCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CardAuthorReqExtCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAuthorizationPubResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAuthorizationPubResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CardAuthorReqCompletedEventHandler(object sender, CardAuthorReqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CardAuthorReqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CardAuthorReqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAuthorizationPubResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAuthorizationPubResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void PmtCardAuthCompletedEventHandler(object sender, PmtCardAuthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PmtCardAuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PmtCardAuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAuthorizationPubResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAuthorizationPubResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CV2PmtCardAuthCompletedEventHandler(object sender, CV2PmtCardAuthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CV2PmtCardAuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CV2PmtCardAuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAuthorizationPubResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAuthorizationPubResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ResortCheckOutReqCompletedEventHandler(object sender, ResortCheckOutReqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResortCheckOutReqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResortCheckOutReqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAuthorizationPubResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAuthorizationPubResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ResortCheckInReqCompletedEventHandler(object sender, ResortCheckInReqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResortCheckInReqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ResortCheckInReqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAuthorizationPubResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAuthorizationPubResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AuthorizeCCCompletedEventHandler(object sender, AuthorizeCCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthorizeCCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthorizeCCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAuthorizationPubResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAuthorizationPubResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AuthorizeCRMCCCompletedEventHandler(object sender, AuthorizeCRMCCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthorizeCRMCCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthorizeCRMCCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAuthorizationPubResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAuthorizationPubResponse)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public CRMAcctInfo CRMInfo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CRMAcctInfo)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CreditCardProcessAuthorReqCompletedEventHandler(object sender, CreditCardProcessAuthorReqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreditCardProcessAuthorReqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreditCardProcessAuthorReqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAuthorizationPubResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAuthorizationPubResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CreditCardProcessAuthorReversalCompletedEventHandler(object sender, CreditCardProcessAuthorReversalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreditCardProcessAuthorReversalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreditCardProcessAuthorReversalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAuthorizationPubResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAuthorizationPubResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void UpdateCardAuthStatusCompletedEventHandler(object sender, UpdateCardAuthStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCardAuthStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCardAuthStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CardAuthorizationPubResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CardAuthorizationPubResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetMerchantByIdCompletedEventHandler(object sender, GetMerchantByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMerchantByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMerchantByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string xmlResponse {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591