//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePlatFront.Resources.Views.Activities {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActivitiesStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActivitiesStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ePlatFront.Resources.Views.Activities.ActivitiesStrings", typeof(ActivitiesStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Length.
        /// </summary>
        public static string Activity_Length {
            get {
                return ResourceManager.GetString("Activity Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Review Now.
        /// </summary>
        public static string Add_a_Review_Now {
            get {
                return ResourceManager.GetString("Add a Review Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adults.
        /// </summary>
        public static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Rating from.
        /// </summary>
        public static string Average_Rating_from {
            get {
                return ResourceManager.GetString("Average Rating from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Babies.
        /// </summary>
        public static string Babies {
            get {
                return ResourceManager.GetString("Babies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be the first reviewing this activity.
        /// </summary>
        public static string Be_the_first {
            get {
                return ResourceManager.GetString("Be the first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOK NOW.
        /// </summary>
        public static string Book_Now {
            get {
                return ResourceManager.GetString("Book Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book This.
        /// </summary>
        public static string Book_This {
            get {
                return ResourceManager.GetString("Book This", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you rate your experience booking your activities with us?.
        /// </summary>
        public static string Booking_Experience {
            get {
                return ResourceManager.GetString("Booking Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLICK HERE TO.
        /// </summary>
        public static string Click_Here_To {
            get {
                return ResourceManager.GetString("Click Here To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to have a legit rank reference, please enter your Payment Confirmation Number to proceed..
        /// </summary>
        public static string Enter_Payment_Confirmation {
            get {
                return ResourceManager.GetString("Enter Payment Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly with.
        /// </summary>
        public static string Friendly_with {
            get {
                return ResourceManager.GetString("Friendly with", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Ranking.
        /// </summary>
        public static string Guest_Ranking {
            get {
                return ResourceManager.GetString("Guest Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿How did we do?.
        /// </summary>
        public static string How_did_we_do {
            get {
                return ResourceManager.GetString("How did we do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOW DO I APPLY IT?.
        /// </summary>
        public static string How_to_Apply {
            get {
                return ResourceManager.GetString("How to Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Itinerary.
        /// </summary>
        public static string Itinerary {
            get {
                return ResourceManager.GetString("Itinerary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Points.
        /// </summary>
        public static string Meeting_Points {
            get {
                return ResourceManager.GetString("Meeting Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Locations.
        /// </summary>
        public static string Multiple_Locations {
            get {
                return ResourceManager.GetString("Multiple Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need More Options?.
        /// </summary>
        public static string Need_More_Options {
            get {
                return ResourceManager.GetString("Need More Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity has not been ranked yet. Be the first to share your experience..
        /// </summary>
        public static string Not_Ranked {
            get {
                return ResourceManager.GetString("Not Ranked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR PRICE.
        /// </summary>
        public static string Our_Price {
            get {
                return ResourceManager.GetString("Our Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Confirmation Number.
        /// </summary>
        public static string Payment_Confirmation_Number {
            get {
                return ResourceManager.GetString("Payment Confirmation Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregnant Women.
        /// </summary>
        public static string Pregnant_Women {
            get {
                return ResourceManager.GetString("Pregnant Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices.
        /// </summary>
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank it now.
        /// </summary>
        public static string Rank_it_now {
            get {
                return ResourceManager.GetString("Rank it now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you rate your experience?.
        /// </summary>
        public static string Rate_your_experience {
            get {
                return ResourceManager.GetString("Rate your experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Reviews.
        /// </summary>
        public static string Read_Reviews {
            get {
                return ResourceManager.GetString("Read Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string Recommendations {
            get {
                return ResourceManager.GetString("Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions.
        /// </summary>
        public static string Restrictions {
            get {
                return ResourceManager.GetString("Restrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETAIL PRICE.
        /// </summary>
        public static string Retail_Price {
            get {
                return ResourceManager.GetString("Retail Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reviews.
        /// </summary>
        public static string reviews {
            get {
                return ResourceManager.GetString("reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVINGS.
        /// </summary>
        public static string Savings {
            get {
                return ResourceManager.GetString("Savings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Details.
        /// </summary>
        public static string See_Details {
            get {
                return ResourceManager.GetString("See Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your File.
        /// </summary>
        public static string Select_your_File {
            get {
                return ResourceManager.GetString("Select your File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seniors.
        /// </summary>
        public static string Seniors {
            get {
                return ResourceManager.GetString("Seniors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share a Picture.
        /// </summary>
        public static string Share_a_Picture {
            get {
                return ResourceManager.GetString("Share a Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a Review.
        /// </summary>
        public static string Share_My_Opinion {
            get {
                return ResourceManager.GetString("Share My Opinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share your Experience.
        /// </summary>
        public static string Share_your_Experience {
            get {
                return ResourceManager.GetString("Share your Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show activities from.
        /// </summary>
        public static string Show_activities_from {
            get {
                return ResourceManager.GetString("Show activities from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will you please take a minute to share your experience?.
        /// </summary>
        public static string Take_a_minute {
            get {
                return ResourceManager.GetString("Take a minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visited on.
        /// </summary>
        public static string Visited_on {
            get {
                return ResourceManager.GetString("Visited on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are always looking for improve our customer service. Please take a minute to evaluate your experience with My Experience Tours..
        /// </summary>
        public static string We_are_always {
            get {
                return ResourceManager.GetString("We are always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is included?.
        /// </summary>
        public static string What_is_included {
            get {
                return ResourceManager.GetString("What is included", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is this about?.
        /// </summary>
        public static string What_is_this_about {
            get {
                return ResourceManager.GetString("What is this about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        public static string Years {
            get {
                return ResourceManager.GetString("Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll save.
        /// </summary>
        public static string Youll_Save {
            get {
                return ResourceManager.GetString("Youll Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Reviews.
        /// </summary>
        public static string Your_Reviews {
            get {
                return ResourceManager.GetString("Your Reviews", resourceCulture);
            }
        }
    }
}
