//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePlatBack.Models.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=187.174.136.121;Initial Catalog=FrontOffice ;User ID=eplatform;Passwo" +
            "rd=3btw4pm7")]
        public string FrontOfficeVDPVEntities {
            get {
                return ((string)(this["FrontOfficeVDPVEntities"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=201.144.24.213;Initial Catalog=FrontOffice ;User ID=crmuser;Password=" +
            "dK6Y7xz3")]
        public string FrontOfficeGBRVEntities {
            get {
                return ((string)(this["FrontOfficeGBRVEntities"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MIGUEL\\SQLEXPRESS;Initial Catalog=ePlatEdgar;User ID=sa;Password=c536" +
            "13b6-c8b8-400d-95c6-274e6e60a14a")]
        public string ePlatEdgarConnectionString {
            get {
                return ((string)(this["ePlatEdgarConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.resortcom.com/ccservice/bankservice.asmx")]
        public string ePlatBack_Models_ccservice_BankService {
            get {
                return ((string)(this["ePlatBack_Models_ccservice_BankService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=187.237.116.38;Initial Catalog=Frontoffice;User ID=crmuser;Password=d" +
            "K6Y7xz3")]
        public string FrontOfficeVDPVCancunEntities {
            get {
                return ((string)(this["FrontOfficeVDPVCancunEntities"]));
            }
        }
    }
}
