//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePlatBack.Models.Resources.Models.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PurchaseTicket {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PurchaseTicket() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ePlatBack.Models.Resources.Models.Shared.PurchaseTicket", typeof(PurchaseTicket).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corresponsal cambiario BBVA Bancomer Institución de Banca Múltiple.
        /// </summary>
        public static string TicketInfo_BankLegend {
            get {
                return ResourceManager.GetString("TicketInfo_BankLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Payments.
        /// </summary>
        public static string TicketInfo_CashPayments {
            get {
                return ResourceManager.GetString("TicketInfo_CashPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Refunds.
        /// </summary>
        public static string TicketInfo_CashRefunds {
            get {
                return ResourceManager.GetString("TicketInfo_CashRefunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Payments.
        /// </summary>
        public static string TicketInfo_CCPayments {
            get {
                return ResourceManager.GetString("TicketInfo_CCPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Refunds.
        /// </summary>
        public static string TicketInfo_CCRefunds {
            get {
                return ResourceManager.GetString("TicketInfo_CCRefunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Due.
        /// </summary>
        public static string TicketInfo_ChangeDue {
            get {
                return ResourceManager.GetString("TicketInfo_ChangeDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must present this ticket to apply for any refunds or cancelations..
        /// </summary>
        public static string TicketInfo_Comments {
            get {
                return ResourceManager.GetString("TicketInfo_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string TicketInfo_Customer {
            get {
                return ResourceManager.GetString("TicketInfo_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued.
        /// </summary>
        public static string TicketInfo_DateIssued {
            get {
                return ResourceManager.GetString("TicketInfo_DateIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string TicketInfo_DateSaved {
            get {
                return ResourceManager.GetString("TicketInfo_DateSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate.
        /// </summary>
        public static string TicketInfo_ExchangeRate {
            get {
                return ResourceManager.GetString("TicketInfo_ExchangeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your purchase..
        /// </summary>
        public static string TicketInfo_Gratitude {
            get {
                return ResourceManager.GetString("TicketInfo_Gratitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string TicketInfo_PointOfSale {
            get {
                return ResourceManager.GetString("TicketInfo_PointOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ticket is not valid as a coupon..
        /// </summary>
        public static string TicketInfo_Policies {
            get {
                return ResourceManager.GetString("TicketInfo_Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Details.
        /// </summary>
        public static string TicketInfo_PurchaseDetails {
            get {
                return ResourceManager.GetString("TicketInfo_PurchaseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Purchase.
        /// </summary>
        public static string TicketInfo_PurchaseTotal {
            get {
                return ResourceManager.GetString("TicketInfo_PurchaseTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string TicketInfo_Services {
            get {
                return ResourceManager.GetString("TicketInfo_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Signature.
        /// </summary>
        public static string TicketInfo_Signature {
            get {
                return ResourceManager.GetString("TicketInfo_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Signature.
        /// </summary>
        public static string TicketInfo_SignatureAgent {
            get {
                return ResourceManager.GetString("TicketInfo_SignatureAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Payments.
        /// </summary>
        public static string TicketInfo_TCPayments {
            get {
                return ResourceManager.GetString("TicketInfo_TCPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC Refunds.
        /// </summary>
        public static string TicketInfo_TCRefunds {
            get {
                return ResourceManager.GetString("TicketInfo_TCRefunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        public static string TicketInfo_TicketNumber {
            get {
                return ResourceManager.GetString("TicketInfo_TicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Paid:.
        /// </summary>
        public static string TicketInfo_TotalPaid {
            get {
                return ResourceManager.GetString("TicketInfo_TotalPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US dollars purchase.
        /// </summary>
        public static string TicketInfo_TotalPaidCashUSD {
            get {
                return ResourceManager.GetString("TicketInfo_TotalPaidCashUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Refund:.
        /// </summary>
        public static string TicketInfo_TotalRefund {
            get {
                return ResourceManager.GetString("TicketInfo_TotalRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Transactions.
        /// </summary>
        public static string TicketInfo_Transactions {
            get {
                return ResourceManager.GetString("TicketInfo_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cashier.
        /// </summary>
        public static string TicketInfo_UserName {
            get {
                return ResourceManager.GetString("TicketInfo_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WT Payments.
        /// </summary>
        public static string TicketInfo_WTPayments {
            get {
                return ResourceManager.GetString("TicketInfo_WTPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WT Refunds.
        /// </summary>
        public static string TicketInfo_WTRefunds {
            get {
                return ResourceManager.GetString("TicketInfo_WTRefunds", resourceCulture);
            }
        }
    }
}
