//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePlatFront.Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ePlatFront.Resources.Views.Shared.SharedStrings", typeof(SharedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string _for {
            get {
                return ResourceManager.GetString("_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved.
        /// </summary>
        public static string All_Rights_Reserved {
            get {
                return ResourceManager.GetString("All Rights Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haven&apos;t decided yet?.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cabo San Lucas Packages.
        /// </summary>
        public static string Cabo_San_Lucas_Packages {
            get {
                return ResourceManager.GetString("Cabo San Lucas Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us help you&lt;br /&gt;&lt;strong&gt;to plan&lt;br /&gt;your vacation&lt;/strong&gt;&lt;br /&gt;Call us &lt;br /&gt;&lt;strong&gt;totally free&lt;/strong&gt;.
        /// </summary>
        public static string Call_Us {
            get {
                return ResourceManager.GetString("Call Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancun Packages.
        /// </summary>
        public static string Cancun_Packages {
            get {
                return ResourceManager.GetString("Cancun Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Form.
        /// </summary>
        public static string Clear_Form {
            get {
                return ResourceManager.GetString("Clear Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        public static string Click_Here {
            get {
                return ResourceManager.GetString("Click Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loreto Packages.
        /// </summary>
        public static string Loreto_Packages {
            get {
                return ResourceManager.GetString("Loreto Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string Mex_About_us {
            get {
                return ResourceManager.GetString("Mex_About_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Total.
        /// </summary>
        public static string Mex_Activity_Total {
            get {
                return ResourceManager.GetString("Mex_Activity Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport Pick Up.
        /// </summary>
        public static string Mex_Airport_Pickup {
            get {
                return ResourceManager.GetString("Mex_Airport_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Airline.
        /// </summary>
        public static string Mex_Arrival_Airline {
            get {
                return ResourceManager.GetString("Mex_Arrival Airline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrival Flight.
        /// </summary>
        public static string Mex_Arrival_Flight {
            get {
                return ResourceManager.GetString("Mex_Arrival Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOOK.
        /// </summary>
        public static string Mex_Book {
            get {
                return ResourceManager.GetString("Mex_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book now or call.
        /// </summary>
        public static string Mex_Book_Now_or_Call {
            get {
                return ResourceManager.GetString("Mex_Book_Now_or_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string Mex_Booking {
            get {
                return ResourceManager.GetString("Mex_Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Rental.
        /// </summary>
        public static string Mex_Car_Rental {
            get {
                return ResourceManager.GetString("Mex_Car Rental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        public static string Mex_CheckOut {
            get {
                return ResourceManager.GetString("Mex_CheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        public static string Mex_Checkout_Customer_Information {
            get {
                return ResourceManager.GetString("Mex_Checkout_Customer_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Information.
        /// </summary>
        public static string Mex_Checkout_Payment_Information {
            get {
                return ResourceManager.GetString("Mex_Checkout_Payment_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Request.
        /// </summary>
        public static string Mex_Checkout_Special {
            get {
                return ResourceManager.GetString("Mex_Checkout_Special", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Time.
        /// </summary>
        public static string Mex_Choose_a_Time {
            get {
                return ResourceManager.GetString("Mex_Choose a Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking &quot;Place Your Order&quot;, you agree to the.
        /// </summary>
        public static string Mex_Click_Place_Order_1 {
            get {
                return ResourceManager.GetString("Mex_Click_Place_Order_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to applicable to your purchase and our.
        /// </summary>
        public static string Mex_Click_Place_Order_2 {
            get {
                return ResourceManager.GetString("Mex_Click_Place_Order_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        public static string Mex_Close {
            get {
                return ResourceManager.GetString("Mex_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Terms.
        /// </summary>
        public static string Mex_Close_Terms {
            get {
                return ResourceManager.GetString("Mex_Close Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Mex_Contact {
            get {
                return ResourceManager.GetString("Mex_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Mex_Continue {
            get {
                return ResourceManager.GetString("Mex_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Mex_Copyright {
            get {
                return ResourceManager.GetString("Mex_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Airline.
        /// </summary>
        public static string Mex_Departure_Airline {
            get {
                return ResourceManager.GetString("Mex_Departure Airline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Date.
        /// </summary>
        public static string Mex_Departure_Date {
            get {
                return ResourceManager.GetString("Mex_Departure Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Flight.
        /// </summary>
        public static string Mex_Departure_Flight {
            get {
                return ResourceManager.GetString("Mex_Departure Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Flight Time.
        /// </summary>
        public static string Mex_Departure_Transportation_Time {
            get {
                return ResourceManager.GetString("Mex_Departure Transportation Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQS.
        /// </summary>
        public static string Mex_FAQS {
            get {
                return ResourceManager.GetString("Mex_FAQS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Checkout.
        /// </summary>
        public static string Mex_Go_to_Checkout {
            get {
                return ResourceManager.GetString("Mex_Go to Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a promotional code?.
        /// </summary>
        public static string Mex_Have_PromoCode {
            get {
                return ResourceManager.GetString("Mex_Have PromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel.
        /// </summary>
        public static string Mex_Hotel {
            get {
                return ResourceManager.GetString("Mex_Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel+Flight.
        /// </summary>
        public static string Mex_Hotel_Flight {
            get {
                return ResourceManager.GetString("Mex_Hotel+Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Only.
        /// </summary>
        public static string Mex_Hotel_Only {
            get {
                return ResourceManager.GetString("Mex_Hotel_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many do you need.
        /// </summary>
        public static string Mex_How_many {
            get {
                return ResourceManager.GetString("Mex_How_many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string Mex_Jobs {
            get {
                return ResourceManager.GetString("Mex_Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land Activities.
        /// </summary>
        public static string Mex_Land_Activities {
            get {
                return ResourceManager.GetString("Mex_Land Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Cam.
        /// </summary>
        public static string Mex_Live_Cam {
            get {
                return ResourceManager.GetString("Mex_Live_Cam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Reservation.
        /// </summary>
        public static string Mex_My_Reservation {
            get {
                return ResourceManager.GetString("Mex_My_Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package.
        /// </summary>
        public static string Mex_Package {
            get {
                return ResourceManager.GetString("Mex_Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay Now.
        /// </summary>
        public static string Mex_Pay_Now {
            get {
                return ResourceManager.GetString("Mex_Pay Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place your Order.
        /// </summary>
        public static string Mex_Place_your_Order {
            get {
                return ResourceManager.GetString("Mex_Place your Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Mex_Policy {
            get {
                return ResourceManager.GetString("Mex_Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRICE.
        /// </summary>
        public static string Mex_Price {
            get {
                return ResourceManager.GetString("Mex_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacidad.
        /// </summary>
        public static string Mex_Privacy {
            get {
                return ResourceManager.GetString("Mex_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /privacy-policy.
        /// </summary>
        public static string Mex_Privacy_Policy_Url {
            get {
                return ResourceManager.GetString("Mex_Privacy Policy Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to Checkout.
        /// </summary>
        public static string Mex_Proceed_to_Checkout {
            get {
                return ResourceManager.GetString("Mex_Proceed to Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTY.
        /// </summary>
        public static string Mex_Qty {
            get {
                return ResourceManager.GetString("Mex_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Terms.
        /// </summary>
        public static string Mex_Read_Terms {
            get {
                return ResourceManager.GetString("Mex_Read Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Request Confirmation.
        /// </summary>
        public static string Mex_Reservation_Request_Confirmation {
            get {
                return ResourceManager.GetString("Mex_Reservation Request Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resort Phone.
        /// </summary>
        public static string Mex_ResortPhone {
            get {
                return ResourceManager.GetString("Mex_ResortPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you need round trip?.
        /// </summary>
        public static string Mex_Round_Trip {
            get {
                return ResourceManager.GetString("Mex_Round_Trip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment confirmation code is:.
        /// </summary>
        public static string Mex_RRC_Text1 {
            get {
                return ResourceManager.GetString("Mex_RRC_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and your credit card has been charged.
        /// </summary>
        public static string Mex_RRC_Text2 {
            get {
                return ResourceManager.GetString("Mex_RRC_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to under the merchant account name .
        /// </summary>
        public static string Mex_RRC_Text3 {
            get {
                return ResourceManager.GetString("Mex_RRC_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A payment confirmation for your approved transaction has been sent to your email address, and you will receive a second email within 48 hours with your coupons and confirmation numbers to print out and present when you attend the excursions. If you do not receive the confirmation within a few minutes, please check your Junk/Spam folder, maybe it got delivered there instead of your inbox..
        /// </summary>
        public static string Mex_RRC_Text4 {
            get {
                return ResourceManager.GetString("Mex_RRC_Text4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you require any further assistance please feel free to contact us at info@myvallartaexperience.com or call us at toll free number &lt;strong&gt;1 877 359 0443 (from USA/Canada) or 01 800 638 7774 (from within Mexico)&lt;/strong&gt;. You may reach us Monday to Friday between 9:00am to 5:00pm and Saturdays and Sundays from 9:00am to 2:00pm Central Standard Time. We will be more than happy to assist you..
        /// </summary>
        public static string Mex_RRC_Text5 {
            get {
                return ResourceManager.GetString("Mex_RRC_Text5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savings.
        /// </summary>
        public static string Mex_Savings {
            get {
                return ResourceManager.GetString("Mex_Savings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Mex_Search {
            get {
                return ResourceManager.GetString("Mex_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEARCH RESULTS.
        /// </summary>
        public static string Mex_Search_Results {
            get {
                return ResourceManager.GetString("Mex_Search Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search your activities.
        /// </summary>
        public static string Mex_Search_your_activities {
            get {
                return ResourceManager.GetString("Mex_Search your activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Date.
        /// </summary>
        public static string Mex_Select_a_Date {
            get {
                return ResourceManager.GetString("Mex_Select a Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        public static string Mex_Shopping_Cart {
            get {
                return ResourceManager.GetString("Mex_Shopping Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talent.
        /// </summary>
        public static string Mex_Talent {
            get {
                return ResourceManager.GetString("Mex_Talent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        public static string Mex_Terms {
            get {
                return ResourceManager.GetString("Mex_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string Mex_Terms_and_Conditions {
            get {
                return ResourceManager.GetString("Mex_Terms_and_Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /terms-and-conditions.
        /// </summary>
        public static string Mex_Terms_Url {
            get {
                return ResourceManager.GetString("Mex_Terms Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toll Free USA/CAN.
        /// </summary>
        public static string Mex_Toll_Free_USA_CAN {
            get {
                return ResourceManager.GetString("Mex_Toll_Free_USA/CAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTALS.
        /// </summary>
        public static string Mex_Totals {
            get {
                return ResourceManager.GetString("Mex_Totals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportation.
        /// </summary>
        public static string Mex_Transportation {
            get {
                return ResourceManager.GetString("Mex_Transportation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Guide.
        /// </summary>
        public static string Mex_Travel_Guide {
            get {
                return ResourceManager.GetString("Mex_Travel Guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Information.
        /// </summary>
        public static string Mex_Travel_Information {
            get {
                return ResourceManager.GetString("Mex_Travel Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNIT.
        /// </summary>
        public static string Mex_Unit {
            get {
                return ResourceManager.GetString("Mex_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the next issues:.
        /// </summary>
        public static string Mex_Validation_Issues {
            get {
                return ResourceManager.GetString("Mex_Validation Issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Virtual.
        /// </summary>
        public static string Mex_Virtual_Tour {
            get {
                return ResourceManager.GetString("Mex_Virtual_Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Activities.
        /// </summary>
        public static string Mex_Water_Activities {
            get {
                return ResourceManager.GetString("Mex_Water Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string Mex_Weather {
            get {
                return ResourceManager.GetString("Mex_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why us?.
        /// </summary>
        public static string Mex_Why_us_ {
            get {
                return ResourceManager.GetString("Mex_Why_us?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string Mex_Zone {
            get {
                return ResourceManager.GetString("Mex_Zone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Info.
        /// </summary>
        public static string More_Info {
            get {
                return ResourceManager.GetString("More Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orlando Packages.
        /// </summary>
        public static string Orlando_Packages {
            get {
                return ResourceManager.GetString("Orlando Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packages.
        /// </summary>
        public static string Packages {
            get {
                return ResourceManager.GetString("Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Privacy_Policy {
            get {
                return ResourceManager.GetString("Privacy Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puerto Vallarta Packages.
        /// </summary>
        public static string Puerto_Vallarta_Packages {
            get {
                return ResourceManager.GetString("Puerto Vallarta Packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a Quote.
        /// </summary>
        public static string Request_a_Quote {
            get {
                return ResourceManager.GetString("Request a Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string Terms_and_Conditions {
            get {
                return ResourceManager.GetString("Terms and Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;Vacation Packages to the Best Destinations&lt;/h1&gt;
        ///            &lt;p&gt;
        ///                At Today Getaway we believe that your vacation should be as affordable as it is relaxing. We are dedicated to providing the absolute &lt;strong&gt;best pricing&lt;/strong&gt; for vacation packages on the market. We will beat any current vacation package price posted on line for any major Mexican resorts, that is our Promise.
        ///            &lt;/p&gt;
        ///            &lt;p&gt;
        ///                The staff at Today Getaway are dedicated professionals who  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TGA_Description {
            get {
                return ResourceManager.GetString("TGA Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see Terms and Conditions of this Offer please.
        /// </summary>
        public static string To_See_Terms {
            get {
                return ResourceManager.GetString("To See Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your hotel name and select to get prices:.
        /// </summary>
        public static string Transportation_Quotes {
            get {
                return ResourceManager.GetString("Transportation_Quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Why people &lt;br /&gt;book with us?&lt;/h4&gt;
        ///                &lt;p&gt;
        ///                    - Best Price Guaranteed&lt;br /&gt;
        ///                    - Secure Transactions&lt;br /&gt;
        ///                    - Flexible Rescheduling Policy&lt;br /&gt;
        ///                    - Customer Service 7 Days a Week&lt;br /&gt;
        ///                    - We work directly with the Resort&lt;br /&gt;
        ///                &lt;/p&gt;.
        /// </summary>
        public static string Why_book_with_us {
            get {
                return ResourceManager.GetString("Why book with us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
