//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ePlatBack.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FrontOfficeVDPVEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FrontOfficeVDPVEntities object using the connection string found in the 'FrontOfficeVDPVEntities' section of the application configuration file.
        /// </summary>
        public FrontOfficeVDPVEntities() : base("name=FrontOfficeVDPVEntities", "FrontOfficeVDPVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FrontOfficeVDPVEntities object.
        /// </summary>
        public FrontOfficeVDPVEntities(string connectionString) : base(connectionString, "FrontOfficeVDPVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FrontOfficeVDPVEntities object.
        /// </summary>
        public FrontOfficeVDPVEntities(EntityConnection connection) : base(connection, "FrontOfficeVDPVEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="fechaInicial">No Metadata Documentation available.</param>
        /// <param name="fechafinal">No Metadata Documentation available.</param>
        public ObjectResult<spLlegadas_Result> spLlegadas(Nullable<global::System.DateTime> fechaInicial, Nullable<global::System.DateTime> fechafinal)
        {
            ObjectParameter fechaInicialParameter;
            if (fechaInicial.HasValue)
            {
                fechaInicialParameter = new ObjectParameter("fechaInicial", fechaInicial);
            }
            else
            {
                fechaInicialParameter = new ObjectParameter("fechaInicial", typeof(global::System.DateTime));
            }
    
            ObjectParameter fechafinalParameter;
            if (fechafinal.HasValue)
            {
                fechafinalParameter = new ObjectParameter("fechafinal", fechafinal);
            }
            else
            {
                fechafinalParameter = new ObjectParameter("fechafinal", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<spLlegadas_Result>("spLlegadas", fechaInicialParameter, fechafinalParameter);
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="FrontOfficeVDPVModel", Name="spLlegadas_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spLlegadas_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spLlegadas_Result object.
        /// </summary>
        /// <param name="x">Initial value of the X property.</param>
        /// <param name="hSalida">Initial value of the HSalida property.</param>
        public static spLlegadas_Result CreatespLlegadas_Result(global::System.Int32 x, global::System.String hSalida)
        {
            spLlegadas_Result spLlegadas_Result = new spLlegadas_Result();
            spLlegadas_Result.X = x;
            spLlegadas_Result.HSalida = hSalida;
            return spLlegadas_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> idReservacion
        {
            get
            {
                return _idReservacion;
            }
            set
            {
                OnidReservacionChanging(value);
                ReportPropertyChanging("idReservacion");
                _idReservacion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idReservacion");
                OnidReservacionChanged();
            }
        }
        private Nullable<global::System.Decimal> _idReservacion;
        partial void OnidReservacionChanging(Nullable<global::System.Decimal> value);
        partial void OnidReservacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CuartosNoche
        {
            get
            {
                return _CuartosNoche;
            }
            set
            {
                OnCuartosNocheChanging(value);
                ReportPropertyChanging("CuartosNoche");
                _CuartosNoche = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CuartosNoche");
                OnCuartosNocheChanged();
            }
        }
        private Nullable<global::System.Int32> _CuartosNoche;
        partial void OnCuartosNocheChanging(Nullable<global::System.Int32> value);
        partial void OnCuartosNocheChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TipoHab
        {
            get
            {
                return _TipoHab;
            }
            set
            {
                OnTipoHabChanging(value);
                ReportPropertyChanging("TipoHab");
                _TipoHab = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TipoHab");
                OnTipoHabChanged();
            }
        }
        private global::System.String _TipoHab;
        partial void OnTipoHabChanging(global::System.String value);
        partial void OnTipoHabChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> llegada
        {
            get
            {
                return _llegada;
            }
            set
            {
                OnllegadaChanging(value);
                ReportPropertyChanging("llegada");
                _llegada = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("llegada");
                OnllegadaChanged();
            }
        }
        private Nullable<global::System.DateTime> _llegada;
        partial void OnllegadaChanging(Nullable<global::System.DateTime> value);
        partial void OnllegadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> salida
        {
            get
            {
                return _salida;
            }
            set
            {
                OnsalidaChanging(value);
                ReportPropertyChanging("salida");
                _salida = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("salida");
                OnsalidaChanged();
            }
        }
        private Nullable<global::System.DateTime> _salida;
        partial void OnsalidaChanging(Nullable<global::System.DateTime> value);
        partial void OnsalidaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NumHab
        {
            get
            {
                return _NumHab;
            }
            set
            {
                OnNumHabChanging(value);
                ReportPropertyChanging("NumHab");
                _NumHab = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NumHab");
                OnNumHabChanged();
            }
        }
        private global::System.String _NumHab;
        partial void OnNumHabChanging(global::System.String value);
        partial void OnNumHabChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numconfirmacion
        {
            get
            {
                return _numconfirmacion;
            }
            set
            {
                OnnumconfirmacionChanging(value);
                ReportPropertyChanging("numconfirmacion");
                _numconfirmacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numconfirmacion");
                OnnumconfirmacionChanged();
            }
        }
        private global::System.String _numconfirmacion;
        partial void OnnumconfirmacionChanging(global::System.String value);
        partial void OnnumconfirmacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Procedencia
        {
            get
            {
                return _Procedencia;
            }
            set
            {
                OnProcedenciaChanging(value);
                ReportPropertyChanging("Procedencia");
                _Procedencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Procedencia");
                OnProcedenciaChanged();
            }
        }
        private global::System.String _Procedencia;
        partial void OnProcedenciaChanging(global::System.String value);
        partial void OnProcedenciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CodigoMerc
        {
            get
            {
                return _CodigoMerc;
            }
            set
            {
                OnCodigoMercChanging(value);
                ReportPropertyChanging("CodigoMerc");
                _CodigoMerc = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CodigoMerc");
                OnCodigoMercChanged();
            }
        }
        private global::System.String _CodigoMerc;
        partial void OnCodigoMercChanging(global::System.String value);
        partial void OnCodigoMercChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> idresort
        {
            get
            {
                return _idresort;
            }
            set
            {
                OnidresortChanging(value);
                ReportPropertyChanging("idresort");
                _idresort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idresort");
                OnidresortChanged();
            }
        }
        private Nullable<global::System.Decimal> _idresort;
        partial void OnidresortChanging(Nullable<global::System.Decimal> value);
        partial void OnidresortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Split
        {
            get
            {
                return _Split;
            }
            set
            {
                OnSplitChanging(value);
                ReportPropertyChanging("Split");
                _Split = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Split");
                OnSplitChanged();
            }
        }
        private Nullable<global::System.Boolean> _Split;
        partial void OnSplitChanging(Nullable<global::System.Boolean> value);
        partial void OnSplitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CRS
        {
            get
            {
                return _CRS;
            }
            set
            {
                OnCRSChanging(value);
                ReportPropertyChanging("CRS");
                _CRS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CRS");
                OnCRSChanged();
            }
        }
        private global::System.String _CRS;
        partial void OnCRSChanging(global::System.String value);
        partial void OnCRSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String codeagencia
        {
            get
            {
                return _codeagencia;
            }
            set
            {
                OncodeagenciaChanging(value);
                ReportPropertyChanging("codeagencia");
                _codeagencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("codeagencia");
                OncodeagenciaChanged();
            }
        }
        private global::System.String _codeagencia;
        partial void OncodeagenciaChanging(global::System.String value);
        partial void OncodeagenciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nameagencia
        {
            get
            {
                return _nameagencia;
            }
            set
            {
                OnnameagenciaChanging(value);
                ReportPropertyChanging("nameagencia");
                _nameagencia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nameagencia");
                OnnameagenciaChanged();
            }
        }
        private global::System.String _nameagencia;
        partial void OnnameagenciaChanging(global::System.String value);
        partial void OnnameagenciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Huesped
        {
            get
            {
                return _Huesped;
            }
            set
            {
                OnHuespedChanging(value);
                ReportPropertyChanging("Huesped");
                _Huesped = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Huesped");
                OnHuespedChanged();
            }
        }
        private global::System.String _Huesped;
        partial void OnHuespedChanging(global::System.String value);
        partial void OnHuespedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> cuartos
        {
            get
            {
                return _cuartos;
            }
            set
            {
                OncuartosChanging(value);
                ReportPropertyChanging("cuartos");
                _cuartos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cuartos");
                OncuartosChanged();
            }
        }
        private Nullable<global::System.Int32> _cuartos;
        partial void OncuartosChanging(Nullable<global::System.Int32> value);
        partial void OncuartosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Adultos
        {
            get
            {
                return _Adultos;
            }
            set
            {
                OnAdultosChanging(value);
                ReportPropertyChanging("Adultos");
                _Adultos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Adultos");
                OnAdultosChanged();
            }
        }
        private Nullable<global::System.Int32> _Adultos;
        partial void OnAdultosChanging(Nullable<global::System.Int32> value);
        partial void OnAdultosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ninos
        {
            get
            {
                return _Ninos;
            }
            set
            {
                OnNinosChanging(value);
                ReportPropertyChanging("Ninos");
                _Ninos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ninos");
                OnNinosChanged();
            }
        }
        private Nullable<global::System.Int32> _Ninos;
        partial void OnNinosChanging(Nullable<global::System.Int32> value);
        partial void OnNinosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellidopaterno
        {
            get
            {
                return _apellidopaterno;
            }
            set
            {
                OnapellidopaternoChanging(value);
                ReportPropertyChanging("apellidopaterno");
                _apellidopaterno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellidopaterno");
                OnapellidopaternoChanged();
            }
        }
        private global::System.String _apellidopaterno;
        partial void OnapellidopaternoChanging(global::System.String value);
        partial void OnapellidopaternoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String apellidomaterno
        {
            get
            {
                return _apellidomaterno;
            }
            set
            {
                OnapellidomaternoChanging(value);
                ReportPropertyChanging("apellidomaterno");
                _apellidomaterno = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("apellidomaterno");
                OnapellidomaternoChanged();
            }
        }
        private global::System.String _apellidomaterno;
        partial void OnapellidomaternoChanging(global::System.String value);
        partial void OnapellidomaternoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombres
        {
            get
            {
                return _nombres;
            }
            set
            {
                OnnombresChanging(value);
                ReportPropertyChanging("nombres");
                _nombres = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombres");
                OnnombresChanged();
            }
        }
        private global::System.String _nombres;
        partial void OnnombresChanging(global::System.String value);
        partial void OnnombresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String codepais
        {
            get
            {
                return _codepais;
            }
            set
            {
                OncodepaisChanging(value);
                ReportPropertyChanging("codepais");
                _codepais = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("codepais");
                OncodepaisChanged();
            }
        }
        private global::System.String _codepais;
        partial void OncodepaisChanging(global::System.String value);
        partial void OncodepaisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String namepais
        {
            get
            {
                return _namepais;
            }
            set
            {
                OnnamepaisChanging(value);
                ReportPropertyChanging("namepais");
                _namepais = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("namepais");
                OnnamepaisChanged();
            }
        }
        private global::System.String _namepais;
        partial void OnnamepaisChanging(global::System.String value);
        partial void OnnamepaisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String codigostatusreservacion
        {
            get
            {
                return _codigostatusreservacion;
            }
            set
            {
                OncodigostatusreservacionChanging(value);
                ReportPropertyChanging("codigostatusreservacion");
                _codigostatusreservacion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("codigostatusreservacion");
                OncodigostatusreservacionChanged();
            }
        }
        private global::System.String _codigostatusreservacion;
        partial void OncodigostatusreservacionChanging(global::System.String value);
        partial void OncodigostatusreservacionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 X
        {
            get
            {
                return _X;
            }
            set
            {
                OnXChanging(value);
                ReportPropertyChanging("X");
                _X = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("X");
                OnXChanged();
            }
        }
        private global::System.Int32 _X;
        partial void OnXChanging(global::System.Int32 value);
        partial void OnXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Titulo
        {
            get
            {
                return _Titulo;
            }
            set
            {
                OnTituloChanging(value);
                ReportPropertyChanging("Titulo");
                _Titulo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Titulo");
                OnTituloChanged();
            }
        }
        private global::System.String _Titulo;
        partial void OnTituloChanging(global::System.String value);
        partial void OnTituloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Infantes
        {
            get
            {
                return _Infantes;
            }
            set
            {
                OnInfantesChanging(value);
                ReportPropertyChanging("Infantes");
                _Infantes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Infantes");
                OnInfantesChanged();
            }
        }
        private Nullable<global::System.Int32> _Infantes;
        partial void OnInfantesChanging(Nullable<global::System.Int32> value);
        partial void OnInfantesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HLlegada
        {
            get
            {
                return _HLlegada;
            }
            set
            {
                OnHLlegadaChanging(value);
                ReportPropertyChanging("HLlegada");
                _HLlegada = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HLlegada");
                OnHLlegadaChanged();
            }
        }
        private global::System.String _HLlegada;
        partial void OnHLlegadaChanging(global::System.String value);
        partial void OnHLlegadaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HSalida
        {
            get
            {
                return _HSalida;
            }
            set
            {
                OnHSalidaChanging(value);
                ReportPropertyChanging("HSalida");
                _HSalida = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("HSalida");
                OnHSalidaChanged();
            }
        }
        private global::System.String _HSalida;
        partial void OnHSalidaChanging(global::System.String value);
        partial void OnHSalidaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> idhuesped
        {
            get
            {
                return _idhuesped;
            }
            set
            {
                OnidhuespedChanging(value);
                ReportPropertyChanging("idhuesped");
                _idhuesped = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idhuesped");
                OnidhuespedChanged();
            }
        }
        private Nullable<global::System.Decimal> _idhuesped;
        partial void OnidhuespedChanging(Nullable<global::System.Decimal> value);
        partial void OnidhuespedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DistintivoPrecheckin
        {
            get
            {
                return _DistintivoPrecheckin;
            }
            set
            {
                OnDistintivoPrecheckinChanging(value);
                ReportPropertyChanging("DistintivoPrecheckin");
                _DistintivoPrecheckin = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DistintivoPrecheckin");
                OnDistintivoPrecheckinChanged();
            }
        }
        private global::System.String _DistintivoPrecheckin;
        partial void OnDistintivoPrecheckinChanging(global::System.String value);
        partial void OnDistintivoPrecheckinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaHoraCheckin
        {
            get
            {
                return _FechaHoraCheckin;
            }
            set
            {
                OnFechaHoraCheckinChanging(value);
                ReportPropertyChanging("FechaHoraCheckin");
                _FechaHoraCheckin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaHoraCheckin");
                OnFechaHoraCheckinChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaHoraCheckin;
        partial void OnFechaHoraCheckinChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaHoraCheckinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contrato
        {
            get
            {
                return _Contrato;
            }
            set
            {
                OnContratoChanging(value);
                ReportPropertyChanging("Contrato");
                _Contrato = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contrato");
                OnContratoChanged();
            }
        }
        private global::System.String _Contrato;
        partial void OnContratoChanging(global::System.String value);
        partial void OnContratoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TipoPlan
        {
            get
            {
                return _TipoPlan;
            }
            set
            {
                OnTipoPlanChanging(value);
                ReportPropertyChanging("TipoPlan");
                _TipoPlan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TipoPlan");
                OnTipoPlanChanged();
            }
        }
        private global::System.String _TipoPlan;
        partial void OnTipoPlanChanging(global::System.String value);
        partial void OnTipoPlanChanged();

        #endregion

    }

    #endregion

    
}
