//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("resortConnectModel", "FK_MemberNote_Reservation", "Reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ePlatBack.Models.Reservation), "MemberNote", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ePlatBack.Models.MemberNote), true)]
[assembly: EdmRelationshipAttribute("resortConnectModel", "FK_Reservation_Contact__Reservation", "Reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ePlatBack.Models.Reservation), "Reservation_Contact", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ePlatBack.Models.Reservation_Contact), true)]
[assembly: EdmRelationshipAttribute("resortConnectModel", "FK_ReservationOption_Reservation", "Reservation", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ePlatBack.Models.Reservation), "ReservationOption", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ePlatBack.Models.ReservationOption), true)]

#endregion

namespace ePlatBack.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class resortConnectEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new resortConnectEntities object using the connection string found in the 'resortConnectEntities' section of the application configuration file.
        /// </summary>
        public resortConnectEntities() : base("name=resortConnectEntities", "resortConnectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new resortConnectEntities object.
        /// </summary>
        public resortConnectEntities(string connectionString) : base(connectionString, "resortConnectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new resortConnectEntities object.
        /// </summary>
        public resortConnectEntities(EntityConnection connection) : base(connection, "resortConnectEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contact> Contact
        {
            get
            {
                if ((_Contact == null))
                {
                    _Contact = base.CreateObjectSet<Contact>("Contact");
                }
                return _Contact;
            }
        }
        private ObjectSet<Contact> _Contact;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MemberNote> MemberNote
        {
            get
            {
                if ((_MemberNote == null))
                {
                    _MemberNote = base.CreateObjectSet<MemberNote>("MemberNote");
                }
                return _MemberNote;
            }
        }
        private ObjectSet<MemberNote> _MemberNote;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reservation> Reservation
        {
            get
            {
                if ((_Reservation == null))
                {
                    _Reservation = base.CreateObjectSet<Reservation>("Reservation");
                }
                return _Reservation;
            }
        }
        private ObjectSet<Reservation> _Reservation;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Reservation_Contact> Reservation_Contact
        {
            get
            {
                if ((_Reservation_Contact == null))
                {
                    _Reservation_Contact = base.CreateObjectSet<Reservation_Contact>("Reservation_Contact");
                }
                return _Reservation_Contact;
            }
        }
        private ObjectSet<Reservation_Contact> _Reservation_Contact;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ReservationOption> ReservationOption
        {
            get
            {
                if ((_ReservationOption == null))
                {
                    _ReservationOption = base.CreateObjectSet<ReservationOption>("ReservationOption");
                }
                return _ReservationOption;
            }
        }
        private ObjectSet<ReservationOption> _ReservationOption;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contact EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContact(Contact contact)
        {
            base.AddObject("Contact", contact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MemberNote EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMemberNote(MemberNote memberNote)
        {
            base.AddObject("MemberNote", memberNote);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reservation EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReservation(Reservation reservation)
        {
            base.AddObject("Reservation", reservation);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reservation_Contact EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReservation_Contact(Reservation_Contact reservation_Contact)
        {
            base.AddObject("Reservation_Contact", reservation_Contact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ReservationOption EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReservationOption(ReservationOption reservationOption)
        {
            base.AddObject("ReservationOption", reservationOption);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="resortConnectModel", Name="Contact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contact object.
        /// </summary>
        /// <param name="contactId">Initial value of the ContactId property.</param>
        /// <param name="primaryFlag">Initial value of the PrimaryFlag property.</param>
        /// <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        public static Contact CreateContact(global::System.Decimal contactId, global::System.Boolean primaryFlag, global::System.DateTime lastUpdated)
        {
            Contact contact = new Contact();
            contact.ContactId = contactId;
            contact.PrimaryFlag = primaryFlag;
            contact.LastUpdated = lastUpdated;
            return contact;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ContactId
        {
            get
            {
                return _ContactId;
            }
            set
            {
                if (_ContactId != value)
                {
                    OnContactIdChanging(value);
                    ReportPropertyChanging("ContactId");
                    _ContactId = StructuralObject.SetValidValue(value, "ContactId");
                    ReportPropertyChanged("ContactId");
                    OnContactIdChanged();
                }
            }
        }
        private global::System.Decimal _ContactId;
        partial void OnContactIdChanging(global::System.Decimal value);
        partial void OnContactIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true, "FirstName");
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true, "LastName");
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BirthDate
        {
            get
            {
                return _BirthDate;
            }
            set
            {
                OnBirthDateChanging(value);
                ReportPropertyChanging("BirthDate");
                _BirthDate = StructuralObject.SetValidValue(value, "BirthDate");
                ReportPropertyChanged("BirthDate");
                OnBirthDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _BirthDate;
        partial void OnBirthDateChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PrimaryFlag
        {
            get
            {
                return _PrimaryFlag;
            }
            set
            {
                OnPrimaryFlagChanging(value);
                ReportPropertyChanging("PrimaryFlag");
                _PrimaryFlag = StructuralObject.SetValidValue(value, "PrimaryFlag");
                ReportPropertyChanged("PrimaryFlag");
                OnPrimaryFlagChanged();
            }
        }
        private global::System.Boolean _PrimaryFlag;
        partial void OnPrimaryFlagChanging(global::System.Boolean value);
        partial void OnPrimaryFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value, "LastUpdated");
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="resortConnectModel", Name="MemberNote")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MemberNote : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MemberNote object.
        /// </summary>
        /// <param name="memberNoteId">Initial value of the MemberNoteId property.</param>
        /// <param name="reservationId">Initial value of the ReservationId property.</param>
        /// <param name="contactId">Initial value of the ContactId property.</param>
        /// <param name="commentType">Initial value of the CommentType property.</param>
        /// <param name="noteDate">Initial value of the NoteDate property.</param>
        /// <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        public static MemberNote CreateMemberNote(global::System.Decimal memberNoteId, global::System.Decimal reservationId, global::System.Decimal contactId, global::System.String commentType, global::System.DateTime noteDate, global::System.DateTime lastUpdated)
        {
            MemberNote memberNote = new MemberNote();
            memberNote.MemberNoteId = memberNoteId;
            memberNote.ReservationId = reservationId;
            memberNote.ContactId = contactId;
            memberNote.CommentType = commentType;
            memberNote.NoteDate = noteDate;
            memberNote.LastUpdated = lastUpdated;
            return memberNote;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MemberNoteId
        {
            get
            {
                return _MemberNoteId;
            }
            set
            {
                if (_MemberNoteId != value)
                {
                    OnMemberNoteIdChanging(value);
                    ReportPropertyChanging("MemberNoteId");
                    _MemberNoteId = StructuralObject.SetValidValue(value, "MemberNoteId");
                    ReportPropertyChanged("MemberNoteId");
                    OnMemberNoteIdChanged();
                }
            }
        }
        private global::System.Decimal _MemberNoteId;
        partial void OnMemberNoteIdChanging(global::System.Decimal value);
        partial void OnMemberNoteIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ReservationId
        {
            get
            {
                return _ReservationId;
            }
            set
            {
                OnReservationIdChanging(value);
                ReportPropertyChanging("ReservationId");
                _ReservationId = StructuralObject.SetValidValue(value, "ReservationId");
                ReportPropertyChanged("ReservationId");
                OnReservationIdChanged();
            }
        }
        private global::System.Decimal _ReservationId;
        partial void OnReservationIdChanging(global::System.Decimal value);
        partial void OnReservationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ContactId
        {
            get
            {
                return _ContactId;
            }
            set
            {
                OnContactIdChanging(value);
                ReportPropertyChanging("ContactId");
                _ContactId = StructuralObject.SetValidValue(value, "ContactId");
                ReportPropertyChanged("ContactId");
                OnContactIdChanged();
            }
        }
        private global::System.Decimal _ContactId;
        partial void OnContactIdChanging(global::System.Decimal value);
        partial void OnContactIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CommentType
        {
            get
            {
                return _CommentType;
            }
            set
            {
                OnCommentTypeChanging(value);
                ReportPropertyChanging("CommentType");
                _CommentType = StructuralObject.SetValidValue(value, false, "CommentType");
                ReportPropertyChanged("CommentType");
                OnCommentTypeChanged();
            }
        }
        private global::System.String _CommentType;
        partial void OnCommentTypeChanging(global::System.String value);
        partial void OnCommentTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NoteDate
        {
            get
            {
                return _NoteDate;
            }
            set
            {
                OnNoteDateChanging(value);
                ReportPropertyChanging("NoteDate");
                _NoteDate = StructuralObject.SetValidValue(value, "NoteDate");
                ReportPropertyChanged("NoteDate");
                OnNoteDateChanged();
            }
        }
        private global::System.DateTime _NoteDate;
        partial void OnNoteDateChanging(global::System.DateTime value);
        partial void OnNoteDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true, "Note");
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value, "LastUpdated");
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("resortConnectModel", "FK_MemberNote_Reservation", "Reservation")]
        public Reservation Reservation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reservation>("resortConnectModel.FK_MemberNote_Reservation", "Reservation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reservation>("resortConnectModel.FK_MemberNote_Reservation", "Reservation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Reservation> ReservationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reservation>("resortConnectModel.FK_MemberNote_Reservation", "Reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Reservation>("resortConnectModel.FK_MemberNote_Reservation", "Reservation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="resortConnectModel", Name="Reservation")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reservation : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reservation object.
        /// </summary>
        /// <param name="reservationId">Initial value of the ReservationId property.</param>
        /// <param name="resortNumber">Initial value of the ResortNumber property.</param>
        /// <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        public static Reservation CreateReservation(global::System.Decimal reservationId, global::System.Int32 resortNumber, global::System.DateTime lastUpdated)
        {
            Reservation reservation = new Reservation();
            reservation.ReservationId = reservationId;
            reservation.ResortNumber = resortNumber;
            reservation.LastUpdated = lastUpdated;
            return reservation;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ReservationId
        {
            get
            {
                return _ReservationId;
            }
            set
            {
                if (_ReservationId != value)
                {
                    OnReservationIdChanging(value);
                    ReportPropertyChanging("ReservationId");
                    _ReservationId = StructuralObject.SetValidValue(value, "ReservationId");
                    ReportPropertyChanged("ReservationId");
                    OnReservationIdChanged();
                }
            }
        }
        private global::System.Decimal _ReservationId;
        partial void OnReservationIdChanging(global::System.Decimal value);
        partial void OnReservationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResortNumber
        {
            get
            {
                return _ResortNumber;
            }
            set
            {
                OnResortNumberChanging(value);
                ReportPropertyChanging("ResortNumber");
                _ResortNumber = StructuralObject.SetValidValue(value, "ResortNumber");
                ReportPropertyChanged("ResortNumber");
                OnResortNumberChanged();
            }
        }
        private global::System.Int32 _ResortNumber;
        partial void OnResortNumberChanging(global::System.Int32 value);
        partial void OnResortNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ConfirmationNumber
        {
            get
            {
                return _ConfirmationNumber;
            }
            set
            {
                OnConfirmationNumberChanging(value);
                ReportPropertyChanging("ConfirmationNumber");
                _ConfirmationNumber = StructuralObject.SetValidValue(value, true, "ConfirmationNumber");
                ReportPropertyChanged("ConfirmationNumber");
                OnConfirmationNumberChanged();
            }
        }
        private global::System.String _ConfirmationNumber;
        partial void OnConfirmationNumberChanging(global::System.String value);
        partial void OnConfirmationNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CheckInDate
        {
            get
            {
                return _CheckInDate;
            }
            set
            {
                OnCheckInDateChanging(value);
                ReportPropertyChanging("CheckInDate");
                _CheckInDate = StructuralObject.SetValidValue(value, "CheckInDate");
                ReportPropertyChanged("CheckInDate");
                OnCheckInDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CheckInDate;
        partial void OnCheckInDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCheckInDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CheckOutDate
        {
            get
            {
                return _CheckOutDate;
            }
            set
            {
                OnCheckOutDateChanging(value);
                ReportPropertyChanging("CheckOutDate");
                _CheckOutDate = StructuralObject.SetValidValue(value, "CheckOutDate");
                ReportPropertyChanged("CheckOutDate");
                OnCheckOutDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CheckOutDate;
        partial void OnCheckOutDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCheckOutDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReservationStatus
        {
            get
            {
                return _ReservationStatus;
            }
            set
            {
                OnReservationStatusChanging(value);
                ReportPropertyChanging("ReservationStatus");
                _ReservationStatus = StructuralObject.SetValidValue(value, true, "ReservationStatus");
                ReportPropertyChanged("ReservationStatus");
                OnReservationStatusChanged();
            }
        }
        private global::System.String _ReservationStatus;
        partial void OnReservationStatusChanging(global::System.String value);
        partial void OnReservationStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ReservationType
        {
            get
            {
                return _ReservationType;
            }
            set
            {
                OnReservationTypeChanging(value);
                ReportPropertyChanging("ReservationType");
                _ReservationType = StructuralObject.SetValidValue(value, true, "ReservationType");
                ReportPropertyChanged("ReservationType");
                OnReservationTypeChanged();
            }
        }
        private global::System.String _ReservationType;
        partial void OnReservationTypeChanging(global::System.String value);
        partial void OnReservationTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UnitTypeId
        {
            get
            {
                return _UnitTypeId;
            }
            set
            {
                OnUnitTypeIdChanging(value);
                ReportPropertyChanging("UnitTypeId");
                _UnitTypeId = StructuralObject.SetValidValue(value, "UnitTypeId");
                ReportPropertyChanged("UnitTypeId");
                OnUnitTypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UnitTypeId;
        partial void OnUnitTypeIdChanging(Nullable<global::System.Int32> value);
        partial void OnUnitTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitTypeName
        {
            get
            {
                return _UnitTypeName;
            }
            set
            {
                OnUnitTypeNameChanging(value);
                ReportPropertyChanging("UnitTypeName");
                _UnitTypeName = StructuralObject.SetValidValue(value, true, "UnitTypeName");
                ReportPropertyChanged("UnitTypeName");
                OnUnitTypeNameChanged();
            }
        }
        private global::System.String _UnitTypeName;
        partial void OnUnitTypeNameChanging(global::System.String value);
        partial void OnUnitTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitTypeDesc
        {
            get
            {
                return _UnitTypeDesc;
            }
            set
            {
                OnUnitTypeDescChanging(value);
                ReportPropertyChanging("UnitTypeDesc");
                _UnitTypeDesc = StructuralObject.SetValidValue(value, true, "UnitTypeDesc");
                ReportPropertyChanged("UnitTypeDesc");
                OnUnitTypeDescChanged();
            }
        }
        private global::System.String _UnitTypeDesc;
        partial void OnUnitTypeDescChanging(global::System.String value);
        partial void OnUnitTypeDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UnitId
        {
            get
            {
                return _UnitId;
            }
            set
            {
                OnUnitIdChanging(value);
                ReportPropertyChanging("UnitId");
                _UnitId = StructuralObject.SetValidValue(value, "UnitId");
                ReportPropertyChanged("UnitId");
                OnUnitIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UnitId;
        partial void OnUnitIdChanging(Nullable<global::System.Int32> value);
        partial void OnUnitIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitDesc
        {
            get
            {
                return _UnitDesc;
            }
            set
            {
                OnUnitDescChanging(value);
                ReportPropertyChanging("UnitDesc");
                _UnitDesc = StructuralObject.SetValidValue(value, true, "UnitDesc");
                ReportPropertyChanged("UnitDesc");
                OnUnitDescChanged();
            }
        }
        private global::System.String _UnitDesc;
        partial void OnUnitDescChanging(global::System.String value);
        partial void OnUnitDescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UnitRef
        {
            get
            {
                return _UnitRef;
            }
            set
            {
                OnUnitRefChanging(value);
                ReportPropertyChanging("UnitRef");
                _UnitRef = StructuralObject.SetValidValue(value, true, "UnitRef");
                ReportPropertyChanged("UnitRef");
                OnUnitRefChanged();
            }
        }
        private global::System.String _UnitRef;
        partial void OnUnitRefChanging(global::System.String value);
        partial void OnUnitRefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ClubType
        {
            get
            {
                return _ClubType;
            }
            set
            {
                OnClubTypeChanging(value);
                ReportPropertyChanging("ClubType");
                _ClubType = StructuralObject.SetValidValue(value, true, "ClubType");
                ReportPropertyChanged("ClubType");
                OnClubTypeChanged();
            }
        }
        private global::System.String _ClubType;
        partial void OnClubTypeChanging(global::System.String value);
        partial void OnClubTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContractNumber
        {
            get
            {
                return _ContractNumber;
            }
            set
            {
                OnContractNumberChanging(value);
                ReportPropertyChanging("ContractNumber");
                _ContractNumber = StructuralObject.SetValidValue(value, true, "ContractNumber");
                ReportPropertyChanged("ContractNumber");
                OnContractNumberChanged();
            }
        }
        private global::System.String _ContractNumber;
        partial void OnContractNumberChanging(global::System.String value);
        partial void OnContractNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> ContractResortNumber
        {
            get
            {
                return _ContractResortNumber;
            }
            set
            {
                OnContractResortNumberChanging(value);
                ReportPropertyChanging("ContractResortNumber");
                _ContractResortNumber = StructuralObject.SetValidValue(value, "ContractResortNumber");
                ReportPropertyChanged("ContractResortNumber");
                OnContractResortNumberChanged();
            }
        }
        private Nullable<global::System.Decimal> _ContractResortNumber;
        partial void OnContractResortNumberChanging(Nullable<global::System.Decimal> value);
        partial void OnContractResortNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PrimaryContactId
        {
            get
            {
                return _PrimaryContactId;
            }
            set
            {
                OnPrimaryContactIdChanging(value);
                ReportPropertyChanging("PrimaryContactId");
                _PrimaryContactId = StructuralObject.SetValidValue(value, "PrimaryContactId");
                ReportPropertyChanged("PrimaryContactId");
                OnPrimaryContactIdChanged();
            }
        }
        private Nullable<global::System.Decimal> _PrimaryContactId;
        partial void OnPrimaryContactIdChanging(Nullable<global::System.Decimal> value);
        partial void OnPrimaryContactIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value, "LastUpdated");
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ClubTypeId
        {
            get
            {
                return _ClubTypeId;
            }
            set
            {
                OnClubTypeIdChanging(value);
                ReportPropertyChanging("ClubTypeId");
                _ClubTypeId = StructuralObject.SetValidValue(value, "ClubTypeId");
                ReportPropertyChanged("ClubTypeId");
                OnClubTypeIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ClubTypeId;
        partial void OnClubTypeIdChanging(Nullable<global::System.Int32> value);
        partial void OnClubTypeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TourBookingStatus
        {
            get
            {
                return _TourBookingStatus;
            }
            set
            {
                OnTourBookingStatusChanging(value);
                ReportPropertyChanging("TourBookingStatus");
                _TourBookingStatus = StructuralObject.SetValidValue(value, "TourBookingStatus");
                ReportPropertyChanged("TourBookingStatus");
                OnTourBookingStatusChanged();
            }
        }
        private Nullable<global::System.Decimal> _TourBookingStatus;
        partial void OnTourBookingStatusChanging(Nullable<global::System.Decimal> value);
        partial void OnTourBookingStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TourBookingStatusDesc
        {
            get
            {
                return _TourBookingStatusDesc;
            }
            set
            {
                OnTourBookingStatusDescChanging(value);
                ReportPropertyChanging("TourBookingStatusDesc");
                _TourBookingStatusDesc = StructuralObject.SetValidValue(value, true, "TourBookingStatusDesc");
                ReportPropertyChanged("TourBookingStatusDesc");
                OnTourBookingStatusDescChanged();
            }
        }
        private global::System.String _TourBookingStatusDesc;
        partial void OnTourBookingStatusDescChanging(global::System.String value);
        partial void OnTourBookingStatusDescChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("resortConnectModel", "FK_MemberNote_Reservation", "MemberNote")]
        public EntityCollection<MemberNote> MemberNote
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MemberNote>("resortConnectModel.FK_MemberNote_Reservation", "MemberNote");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MemberNote>("resortConnectModel.FK_MemberNote_Reservation", "MemberNote", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("resortConnectModel", "FK_Reservation_Contact__Reservation", "Reservation_Contact")]
        public EntityCollection<Reservation_Contact> Reservation_Contact
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Reservation_Contact>("resortConnectModel.FK_Reservation_Contact__Reservation", "Reservation_Contact");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Reservation_Contact>("resortConnectModel.FK_Reservation_Contact__Reservation", "Reservation_Contact", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("resortConnectModel", "FK_ReservationOption_Reservation", "ReservationOption")]
        public EntityCollection<ReservationOption> ReservationOption
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ReservationOption>("resortConnectModel.FK_ReservationOption_Reservation", "ReservationOption");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ReservationOption>("resortConnectModel.FK_ReservationOption_Reservation", "ReservationOption", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="resortConnectModel", Name="Reservation_Contact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Reservation_Contact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Reservation_Contact object.
        /// </summary>
        /// <param name="reservation_ContactId">Initial value of the Reservation_ContactId property.</param>
        /// <param name="reservationId">Initial value of the ReservationId property.</param>
        /// <param name="contactId">Initial value of the ContactId property.</param>
        /// <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        public static Reservation_Contact CreateReservation_Contact(global::System.Decimal reservation_ContactId, global::System.Decimal reservationId, global::System.Decimal contactId, global::System.DateTime lastUpdated)
        {
            Reservation_Contact reservation_Contact = new Reservation_Contact();
            reservation_Contact.Reservation_ContactId = reservation_ContactId;
            reservation_Contact.ReservationId = reservationId;
            reservation_Contact.ContactId = contactId;
            reservation_Contact.LastUpdated = lastUpdated;
            return reservation_Contact;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Reservation_ContactId
        {
            get
            {
                return _Reservation_ContactId;
            }
            set
            {
                if (_Reservation_ContactId != value)
                {
                    OnReservation_ContactIdChanging(value);
                    ReportPropertyChanging("Reservation_ContactId");
                    _Reservation_ContactId = StructuralObject.SetValidValue(value, "Reservation_ContactId");
                    ReportPropertyChanged("Reservation_ContactId");
                    OnReservation_ContactIdChanged();
                }
            }
        }
        private global::System.Decimal _Reservation_ContactId;
        partial void OnReservation_ContactIdChanging(global::System.Decimal value);
        partial void OnReservation_ContactIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ReservationId
        {
            get
            {
                return _ReservationId;
            }
            set
            {
                OnReservationIdChanging(value);
                ReportPropertyChanging("ReservationId");
                _ReservationId = StructuralObject.SetValidValue(value, "ReservationId");
                ReportPropertyChanged("ReservationId");
                OnReservationIdChanged();
            }
        }
        private global::System.Decimal _ReservationId;
        partial void OnReservationIdChanging(global::System.Decimal value);
        partial void OnReservationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ContactId
        {
            get
            {
                return _ContactId;
            }
            set
            {
                OnContactIdChanging(value);
                ReportPropertyChanging("ContactId");
                _ContactId = StructuralObject.SetValidValue(value, "ContactId");
                ReportPropertyChanged("ContactId");
                OnContactIdChanged();
            }
        }
        private global::System.Decimal _ContactId;
        partial void OnContactIdChanging(global::System.Decimal value);
        partial void OnContactIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value, "LastUpdated");
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, true, "PhoneNumber");
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, true, "EmailAddress");
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("resortConnectModel", "FK_Reservation_Contact__Reservation", "Reservation")]
        public Reservation Reservation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reservation>("resortConnectModel.FK_Reservation_Contact__Reservation", "Reservation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reservation>("resortConnectModel.FK_Reservation_Contact__Reservation", "Reservation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Reservation> ReservationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reservation>("resortConnectModel.FK_Reservation_Contact__Reservation", "Reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Reservation>("resortConnectModel.FK_Reservation_Contact__Reservation", "Reservation", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="resortConnectModel", Name="ReservationOption")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ReservationOption : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ReservationOption object.
        /// </summary>
        /// <param name="reservationOptionId">Initial value of the ReservationOptionId property.</param>
        /// <param name="reservationId">Initial value of the ReservationId property.</param>
        /// <param name="lastUpdated">Initial value of the LastUpdated property.</param>
        public static ReservationOption CreateReservationOption(global::System.Decimal reservationOptionId, global::System.Decimal reservationId, global::System.DateTime lastUpdated)
        {
            ReservationOption reservationOption = new ReservationOption();
            reservationOption.ReservationOptionId = reservationOptionId;
            reservationOption.ReservationId = reservationId;
            reservationOption.LastUpdated = lastUpdated;
            return reservationOption;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ReservationOptionId
        {
            get
            {
                return _ReservationOptionId;
            }
            set
            {
                if (_ReservationOptionId != value)
                {
                    OnReservationOptionIdChanging(value);
                    ReportPropertyChanging("ReservationOptionId");
                    _ReservationOptionId = StructuralObject.SetValidValue(value, "ReservationOptionId");
                    ReportPropertyChanged("ReservationOptionId");
                    OnReservationOptionIdChanged();
                }
            }
        }
        private global::System.Decimal _ReservationOptionId;
        partial void OnReservationOptionIdChanging(global::System.Decimal value);
        partial void OnReservationOptionIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal ReservationId
        {
            get
            {
                return _ReservationId;
            }
            set
            {
                OnReservationIdChanging(value);
                ReportPropertyChanging("ReservationId");
                _ReservationId = StructuralObject.SetValidValue(value, "ReservationId");
                ReportPropertyChanged("ReservationId");
                OnReservationIdChanged();
            }
        }
        private global::System.Decimal _ReservationId;
        partial void OnReservationIdChanging(global::System.Decimal value);
        partial void OnReservationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProductName
        {
            get
            {
                return _ProductName;
            }
            set
            {
                OnProductNameChanging(value);
                ReportPropertyChanging("ProductName");
                _ProductName = StructuralObject.SetValidValue(value, true, "ProductName");
                ReportPropertyChanged("ProductName");
                OnProductNameChanged();
            }
        }
        private global::System.String _ProductName;
        partial void OnProductNameChanging(global::System.String value);
        partial void OnProductNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> AppointmentDate
        {
            get
            {
                return _AppointmentDate;
            }
            set
            {
                OnAppointmentDateChanging(value);
                ReportPropertyChanging("AppointmentDate");
                _AppointmentDate = StructuralObject.SetValidValue(value, "AppointmentDate");
                ReportPropertyChanged("AppointmentDate");
                OnAppointmentDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _AppointmentDate;
        partial void OnAppointmentDateChanging(Nullable<global::System.DateTime> value);
        partial void OnAppointmentDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CarrierName
        {
            get
            {
                return _CarrierName;
            }
            set
            {
                OnCarrierNameChanging(value);
                ReportPropertyChanging("CarrierName");
                _CarrierName = StructuralObject.SetValidValue(value, true, "CarrierName");
                ReportPropertyChanged("CarrierName");
                OnCarrierNameChanged();
            }
        }
        private global::System.String _CarrierName;
        partial void OnCarrierNameChanging(global::System.String value);
        partial void OnCarrierNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FlightNumber
        {
            get
            {
                return _FlightNumber;
            }
            set
            {
                OnFlightNumberChanging(value);
                ReportPropertyChanging("FlightNumber");
                _FlightNumber = StructuralObject.SetValidValue(value, true, "FlightNumber");
                ReportPropertyChanged("FlightNumber");
                OnFlightNumberChanged();
            }
        }
        private global::System.String _FlightNumber;
        partial void OnFlightNumberChanging(global::System.String value);
        partial void OnFlightNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Quantity
        {
            get
            {
                return _Quantity;
            }
            set
            {
                OnQuantityChanging(value);
                ReportPropertyChanging("Quantity");
                _Quantity = StructuralObject.SetValidValue(value, "Quantity");
                ReportPropertyChanged("Quantity");
                OnQuantityChanged();
            }
        }
        private Nullable<global::System.Int32> _Quantity;
        partial void OnQuantityChanging(Nullable<global::System.Int32> value);
        partial void OnQuantityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BaseCurrencyAmount
        {
            get
            {
                return _BaseCurrencyAmount;
            }
            set
            {
                OnBaseCurrencyAmountChanging(value);
                ReportPropertyChanging("BaseCurrencyAmount");
                _BaseCurrencyAmount = StructuralObject.SetValidValue(value, true, "BaseCurrencyAmount");
                ReportPropertyChanged("BaseCurrencyAmount");
                OnBaseCurrencyAmountChanged();
            }
        }
        private global::System.String _BaseCurrencyAmount;
        partial void OnBaseCurrencyAmountChanging(global::System.String value);
        partial void OnBaseCurrencyAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Note
        {
            get
            {
                return _Note;
            }
            set
            {
                OnNoteChanging(value);
                ReportPropertyChanging("Note");
                _Note = StructuralObject.SetValidValue(value, true, "Note");
                ReportPropertyChanged("Note");
                OnNoteChanged();
            }
        }
        private global::System.String _Note;
        partial void OnNoteChanging(global::System.String value);
        partial void OnNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdated
        {
            get
            {
                return _LastUpdated;
            }
            set
            {
                OnLastUpdatedChanging(value);
                ReportPropertyChanging("LastUpdated");
                _LastUpdated = StructuralObject.SetValidValue(value, "LastUpdated");
                ReportPropertyChanged("LastUpdated");
                OnLastUpdatedChanged();
            }
        }
        private global::System.DateTime _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.DateTime value);
        partial void OnLastUpdatedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("resortConnectModel", "FK_ReservationOption_Reservation", "Reservation")]
        public Reservation Reservation
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reservation>("resortConnectModel.FK_ReservationOption_Reservation", "Reservation").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reservation>("resortConnectModel.FK_ReservationOption_Reservation", "Reservation").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Reservation> ReservationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Reservation>("resortConnectModel.FK_ReservationOption_Reservation", "Reservation");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Reservation>("resortConnectModel.FK_ReservationOption_Reservation", "Reservation", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
