//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePlatBack.Models.Resources.Models.Coupon {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CouponStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CouponStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ePlatBack.Models.Resources.Models.Coupon.CouponStrings", typeof(CouponStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Name.
        /// </summary>
        public static string Activity_Name {
            get {
                return ResourceManager.GetString("Activity Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity/Service.
        /// </summary>
        public static string Activity_Service {
            get {
                return ResourceManager.GetString("Activity_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity/Service Date.
        /// </summary>
        public static string Activity_Service_Date {
            get {
                return ResourceManager.GetString("Activity_Service_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Time.
        /// </summary>
        public static string Activity_Time {
            get {
                return ResourceManager.GetString("Activity Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline:.
        /// </summary>
        public static string Airline {
            get {
                return ResourceManager.GetString("Airline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport:.
        /// </summary>
        public static string Airport {
            get {
                return ResourceManager.GetString("Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Number.
        /// </summary>
        public static string Confirmation_Number {
            get {
                return ResourceManager.GetString("Confirmation Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;&lt;li&gt;Valid only for specified date and time.&lt;/li&gt;
        ///&lt;li&gt;Please note this coupon validates your reservation so make sure you keep it in a safe place and don&apos;t forget to bring it with you.&lt;/li&gt;
        ///&lt;/ul&gt;.
        /// </summary>
        public static string Coupon_Note {
            get {
                return ResourceManager.GetString("Coupon Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Number.
        /// </summary>
        public static string Coupon_Number {
            get {
                return ResourceManager.GetString("Coupon Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Location.
        /// </summary>
        public static string Delivery_Location {
            get {
                return ResourceManager.GetString("Delivery Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Time.
        /// </summary>
        public static string Delivery_Time {
            get {
                return ResourceManager.GetString("Delivery Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Rate.
        /// </summary>
        public static string Exchange_Rate {
            get {
                return ResourceManager.GetString("Exchange Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight:.
        /// </summary>
        public static string Flight {
            get {
                return ResourceManager.GetString("Flight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Time:.
        /// </summary>
        public static string Flight_Time {
            get {
                return ResourceManager.GetString("Flight Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good for.
        /// </summary>
        public static string Good_for {
            get {
                return ResourceManager.GetString("Good for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Name.
        /// </summary>
        public static string Guest_Name {
            get {
                return ResourceManager.GetString("Guest Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel:.
        /// </summary>
        public static string Hotel {
            get {
                return ResourceManager.GetString("Hotel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMPORTANT.
        /// </summary>
        public static string Important {
            get {
                return ResourceManager.GetString("Important", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operated by.
        /// </summary>
        public static string Is_operated_by {
            get {
                return ResourceManager.GetString("Is operated by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Point.
        /// </summary>
        public static string Meeting_Point {
            get {
                return ResourceManager.GetString("Meeting Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Time.
        /// </summary>
        public static string Meeting_Time {
            get {
                return ResourceManager.GetString("Meeting Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modality of operation: Retail Agency.
        /// </summary>
        public static string Modality {
            get {
                return ResourceManager.GetString("Modality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTES.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printed By.
        /// </summary>
        public static string PrintedBy {
            get {
                return ResourceManager.GetString("PrintedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string PrintedOn {
            get {
                return ResourceManager.GetString("PrintedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Privacy_Policy {
            get {
                return ResourceManager.GetString("Privacy Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Phone.
        /// </summary>
        public static string Provider_Phone {
            get {
                return ResourceManager.GetString("Provider_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Date (internal use).
        /// </summary>
        public static string Purchase_Date {
            get {
                return ResourceManager.GetString("Purchase Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations.
        /// </summary>
        public static string Recommendations {
            get {
                return ResourceManager.GetString("Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security String.
        /// </summary>
        public static string Security_String {
            get {
                return ResourceManager.GetString("Security String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Service_Time {
            get {
                return ResourceManager.GetString("Service Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicited Vehicle.
        /// </summary>
        public static string Solicited_Vehicle {
            get {
                return ResourceManager.GetString("Solicited Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        public static string Terms_and_Conditions {
            get {
                return ResourceManager.GetString("Terms and Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be confirmed.
        /// </summary>
        public static string To_be_confirmed {
            get {
                return ResourceManager.GetString("To be confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need assistance?.
        /// </summary>
        public static string Toll_Free {
            get {
                return ResourceManager.GetString("Toll Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction ID.
        /// </summary>
        public static string Transaction_ID {
            get {
                return ResourceManager.GetString("Transaction ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear guest, for a better reference at the time of your arrival our drivers wear a blue polo shirt with the &quot;Cabo Seasons&quot; logo and beige color pants..
        /// </summary>
        public static string Transportation_Note {
            get {
                return ResourceManager.GetString("Transportation Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel Info.
        /// </summary>
        public static string Travel_Info {
            get {
                return ResourceManager.GetString("Travel Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid for.
        /// </summary>
        public static string Valid_for {
            get {
                return ResourceManager.GetString("Valid for", resourceCulture);
            }
        }
    }
}
