//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePlatFront.Resources.Views.Packages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PackagesStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackagesStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ePlatFront.Resources.Views.Packages.PackagesStrings", typeof(PackagesStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the Resort.
        /// </summary>
        public static string About_the_Resort {
            get {
                return ResourceManager.GetString("About the Resort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adults.
        /// </summary>
        public static string adults {
            get {
                return ResourceManager.GetString("adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What all inclusive means?.
        /// </summary>
        public static string All_Inclusive_Meaning {
            get {
                return ResourceManager.GetString("All Inclusive Meaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amenities.
        /// </summary>
        public static string Amenities {
            get {
                return ResourceManager.GetString("Amenities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any doubt? Read the F.A.Q..
        /// </summary>
        public static string Any_doubt {
            get {
                return ResourceManager.GetString("Any doubt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        public static string Book_Now {
            get {
                return ResourceManager.GetString("Book Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Today.
        /// </summary>
        public static string Book_Today {
            get {
                return ResourceManager.GetString("Book Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Now.
        /// </summary>
        public static string Call_Now {
            get {
                return ResourceManager.GetString("Call Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Our Toll Free Number.
        /// </summary>
        public static string Call_Our_Toll_Free_Number {
            get {
                return ResourceManager.GetString("Call Our Toll Free Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to children.
        /// </summary>
        public static string children {
            get {
                return ResourceManager.GetString("children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        public static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decide travel dates later.
        /// </summary>
        public static string Decide_travel_dates_later {
            get {
                return ResourceManager.GetString("Decide travel dates later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.A.Q..
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for only.
        /// </summary>
        public static string for_only {
            get {
                return ResourceManager.GetString("for only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nights.
        /// </summary>
        public static string nights {
            get {
                return ResourceManager.GetString("nights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Package Price. Not Per Night, Not Per Person..
        /// </summary>
        public static string Package_Price_Terms {
            get {
                return ResourceManager.GetString("Package Price Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RETAILPRICE.
        /// </summary>
        public static string RETAIL_PRICE {
            get {
                return ResourceManager.GetString("RETAIL PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Resort.
        /// </summary>
        public static string The_Resort {
            get {
                return ResourceManager.GetString("The Resort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Room.
        /// </summary>
        public static string Your_Room {
            get {
                return ResourceManager.GetString("Your Room", resourceCulture);
            }
        }
    }
}
