//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePlatBack.Models.Resources.Models.Promo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PromoStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PromoStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ePlatBack.Models.Resources.Models.Promo.PromoStrings", typeof(PromoStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have activities in your Shopping Cart that apply for a Promo. In order to take advantage of the 2x1 Promo you need to have at least 2 activities in your shopping cart that participate in the same promo and with the same number of participants..
        /// </summary>
        public static string Condition_2x1 {
            get {
                return ResourceManager.GetString("Condition_2x1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have activities in your Shopping Cart that apply for a Promo. In order to take advantage of the 3x2 Promo you need to have at least 3 activities in your shopping cart that participate in the same promo and with the same number of participants..
        /// </summary>
        public static string Condition_3x2 {
            get {
                return ResourceManager.GetString("Condition_3x2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have activities in your Shopping Cart that apply for a Promo. In order to take advantage of the 4x3 Promo you need to have at least 4 activities in your shopping cart that participate in the same promo and with the same number of participants..
        /// </summary>
        public static string Condition_4x3 {
            get {
                return ResourceManager.GetString("Condition_4x3", resourceCulture);
            }
        }
    }
}
