var Language = {
    Applied_to: ' ha sido aplicada a ',
    And: 'y',
    At: 'a las',
    Booking: 'Reservando',
    Check_Issues: 'Por favor revisa los siguientes campos:',
    Editing: 'Editando',
    Field_Date: 'Necesitas especificar una fecha para tu actividad.',
    Field_Schedule: 'Elige tu horario.',
    Field_Hotel: 'Necesitas seleccionar tu hotel.',
    Field_Zone: 'Necesitas seleccionar una zona.',
    Field_Airline: 'Por favor escribe la aerolínea.',
    Field_FlightNumber: 'Por favor especifica el número de vuelo.',
    Field_RoundDate: 'Por favor especifica la fecha de retorno.',
    Field_RoundAirline: 'Por favor escriba la aerolínea de retorno.',
    Field_RoundFlightNumber: 'Por favor especifica el número de vuelo de retorno.',
    Field_RoundTime: 'Selecciona la hora del vuelo de retorno.',
    Field_Details: 'Necesitas especificar los participantes para calcular el costo.',
    File_Selected: 'Archivo Seleccionado',
    Getting_Availability: 'Revisando Horarios Disponibles',
    Getting_Prices: 'Obteniendo Precios',
    Go_to_Checkout: 'Proceder a Pagar',
    I_hate_it: 'Lo odié',
    I_dont_like_it: 'No me gustó',
    Its_okay: 'Está bien',
    I_like_it: 'Me gustó',
    I_love_it: 'Me encantó',
    In_the_last_24_hours: ' en las últimas 24 horas.',
    No_Activities: 'No hay actividades en tu carrito.',
    People_are_browsing: ' personas están viendo ',
    People_have_purchased: ' personas han comprado ',
    Processing: 'Redirigiendo a portal de pago seguro...',
    Promo_Applied: 'PROMOCIÓN APLICADA',
    Purchase_Error: 'Ha ocurrido un error al guardar tu compra. Haz clic en pagar después para enviarnos los datos de tu compra y te contactaremos para efectuar tu pago.',
    Right_now: ' en este momento.',
    Search_by_Name: 'Coincidencias en Nombre',
    Search_in_Content: 'Coincidencias en Contenido',
    Search_by_Meeting_Point: 'Coincidencias en Punto de Reunión',
    Search_by_Provider: 'Coincidencias en Proveedor',
    Select_your_File: 'Elige tu Foto',
    Sending: 'Enviando',
    Submit: 'Enviar',
    Transportation_Getting_Prices: 'Obteniendo Precios...',
    Transportation_No_Results: 'La búsqueda no arrojó resultados. Contáctanos por teléfono para ayudarte.',
    Temporal_Alert_Content: 'Queridos amigos y clientes, debido a temporada alta los espacios disponibles en nuestros tours se están llenando rápidamente, tanto fechas como horarios están sujetos a disponibilidad y es posible que tengamos que recomendarles o cambiarles el día o el horario que originalmente eligen. Les recomendamos planear su viaje y reservar sus actividades  tan pronto como sea posible, si necesitan asistencia no duden en llamarnos, estamos para servirles.',
    Temporal_Alert_Title: 'Quedan pocos espacios',
    Total_More_Than_Zero: 'El Total debe ser mayor a 0',
    Uploading_File: 'Subiendo Foto',
    Wait_Please: 'Espera por favor'
};