var Language = {
    Applied_to: ' has been applied to ',
    And: 'and',
    At: 'at',    
    Booking: 'Booking',
    Check_Issues: 'Please check the next issues:',
    Editing: 'Editing',
    Field_Date: 'You need to specify a date for your activity.',
    Field_Schedule: 'Select an schedule.',
    Field_Hotel: 'You need to select a hotel.',
    Field_Zone: 'You need to select a zone.',
    Field_Airline: 'Please enter the airline.',
    Field_FlightNumber: 'Please specify the flight number.',
    Field_RoundDate: 'Please specify your departure date.',
    Field_RoundAirline: 'Please enter the departure airline.',
    Field_RoundFlightNumber: 'Please specify the departure flight number.',
    Field_RoundTime: 'Select your departure flight time.',
    Field_Details: 'You have to specify the details to calculate the cost.',
    File_Selected: 'File Selected',
    Getting_Availability: 'Getting Availability',
    Getting_Prices: 'Getting Prices',
    Go_to_Checkout: 'Go to Checkout',
    I_hate_it: 'I hate it',
    I_dont_like_it: 'I don\'t like it',
    Its_okay: 'It\'s okay',
    I_like_it: 'I like it',
    I_love_it: 'I love it',
    In_the_last_24_hours: ' in the last 24 hours.',
    No_Activities: 'Your Shopping Cart is empty.',
    People_are_browsing: ' people are browsing ',
    People_have_purchased: ' people have purchased ',
    Processing: 'Processing your payment. It can take a minute, please wait',
    Promo_Applied: 'PROMO APPLIED',
    Purchase_Error: 'An error ocurred trying to process your purchase. Click Pay Later to send us your shopping cart and we will contact you soon to process your payment.',
    Right_now: ' right now.',
    Search_by_Name: 'Search by Name',
    Search_in_Content: 'Search in Content',
    Search_by_Meeting_Point: 'Search by Meeting Point',
    Search_by_Provider: 'Search by Provider',
    Select_your_File: 'Select your File',
    Sending: 'Sending',
    Submit: 'Submit',
    Transportation_Getting_Prices: 'Getting Prices...',
    Transportation_No_Results: 'Search did not get results. Contact us by phone to help you.',
    Temporal_Alert_Content: 'Dear Friends and Customers, due to high season all our spaces fill out quickly, please note that both dates and schedules are subject to availability and we might have to recommend and accomodate you in a different day or schedule as initially chosen. We recommend you to plan your trip and book your activities as soon as conveniently possible, if you need any assistance please do not hesitate, we are glad to help.',
    Temporal_Alert_Title: 'Few Spaces Left',
    Total_More_Than_Zero: 'Total must be bigger than zero',
    Uploading_File: 'Uploading File',
    Wait_Please: 'Wait Please'
};