//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePlatBack.Models.Resources.Models.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubmitReview {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmitReview() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ePlatBack.Models.Resources.Models.Controls.SubmitReview", typeof(SubmitReview).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Confirmation Number.
        /// </summary>
        public static string AuthCode {
            get {
                return ResourceManager.GetString("AuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to specify your Payment Confirmation Number.
        /// </summary>
        public static string AuthCode_Required {
            get {
                return ResourceManager.GetString("AuthCode_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s your name?.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name is required.
        /// </summary>
        public static string Author_Required {
            get {
                return ResourceManager.GetString("Author_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you from?.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location is required.
        /// </summary>
        public static string From_Required {
            get {
                return ResourceManager.GetString("From_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you rank your experience?.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating is required.
        /// </summary>
        public static string Rating_Required {
            get {
                return ResourceManager.GetString("Rating_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us your experience.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review is required.
        /// </summary>
        public static string Review_Required {
            get {
                return ResourceManager.GetString("Review_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for sharing your experience! We are validating your review and will be posted in the next 24 hours..
        /// </summary>
        public static string Review_Success {
            get {
                return ResourceManager.GetString("Review_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something weird happened trying to save your information, please try again..
        /// </summary>
        public static string Submit_Fails {
            get {
                return ResourceManager.GetString("Submit_Fails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your evaluation and feedback! We really appreciate it and hope to serve you in the near future..
        /// </summary>
        public static string Submit_Feedback_Success {
            get {
                return ResourceManager.GetString("Submit_Feedback_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Survey was already answered. Thank you!.
        /// </summary>
        public static string Survey_Answered {
            get {
                return ResourceManager.GetString("Survey_Answered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. This is not a registered Survey URL..
        /// </summary>
        public static string Survey_Not_Registered {
            get {
                return ResourceManager.GetString("Survey_Not_Registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry. This is not a valid Survey..
        /// </summary>
        public static string Survey_Not_Valid {
            get {
                return ResourceManager.GetString("Survey_Not_Valid", resourceCulture);
            }
        }
    }
}
